/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentList {
    /// Список контента
    #[serde(rename = "items")]
    pub items: Vec<models::Content>,
    /// Общее количество записей, соответствующих заданным критериям выборки.  Параметры: - `take` (integer): Количество записей, которые необходимо вернуть в текущем ответе. Например, если `take` равно 10, то в ответе будет не более 10 записей. - `skip` (integer): Количество записей, которые необходимо пропустить перед началом выборки. Например, если `skip` равно 20, то выборка начнется с 21 записи.  Поле `total` показывает полное количество записей, соответствующих условиям фильтрации, без учета параметров `take` и `skip` 
    #[serde(rename = "total")]
    pub total: i64,
}

impl ContentList {
    pub fn new(items: Vec<models::Content>, total: i64) -> ContentList {
        ContentList {
            items,
            total,
        }
    }
}

