/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentMeta : Метаданные. Дополнительная информация о контенте 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentMeta {
    /// URI адреса обложки контента
    #[serde(rename = "thumbnail")]
    pub thumbnail: Vec<String>,
    /// Имя исходного файла
    #[serde(rename = "source_file_name", skip_serializing_if = "Option::is_none")]
    pub source_file_name: Option<String>,
    /// Возрастное ограничение
    #[serde(rename = "rating", skip_serializing_if = "Option::is_none")]
    pub rating: Option<Rating>,
    /// Оригинальное название контента
    #[serde(rename = "original_name", skip_serializing_if = "Option::is_none")]
    pub original_name: Option<String>,
    /// Актер озвучивающий аудиоконтент
    #[serde(rename = "voice", skip_serializing_if = "Option::is_none")]
    pub voice: Option<String>,
    /// [ISBN](https://en.wikipedia.org/wiki/ISBN) (Международный стандартный книжный номер) - Каждый ISBN уникален - Состоит из 13 символов, начиная с префикса **978** или **979** 
    #[serde(rename = "bisac", skip_serializing_if = "Option::is_none")]
    pub bisac: Option<String>,
    /// Количество страниц в книге (файле)
    #[serde(rename = "pages", skip_serializing_if = "Option::is_none")]
    pub pages: Option<i32>,
    /// Автор контента
    #[serde(rename = "author", skip_serializing_if = "Option::is_none")]
    pub author: Option<String>,
    /// Переводчик 
    #[serde(rename = "translator", skip_serializing_if = "Option::is_none")]
    pub translator: Option<String>,
    /// Продолжительность контента
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<String>,
}

impl ContentMeta {
    /// Метаданные. Дополнительная информация о контенте 
    pub fn new(thumbnail: Vec<String>) -> ContentMeta {
        ContentMeta {
            thumbnail,
            source_file_name: None,
            rating: None,
            original_name: None,
            voice: None,
            bisac: None,
            pages: None,
            author: None,
            translator: None,
            duration: None,
        }
    }
}
/// Возрастное ограничение
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Rating {
    #[serde(rename = "0+")]
    Variant0Plus,
    #[serde(rename = "6+")]
    Variant6Plus,
    #[serde(rename = "12+")]
    Variant12Plus,
    #[serde(rename = "14+")]
    Variant14Plus,
    #[serde(rename = "16+")]
    Variant16Plus,
    #[serde(rename = "18+")]
    Variant18Plus,
}

impl Default for Rating {
    fn default() -> Rating {
        Self::Variant0Plus
    }
}

