/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentDeleteRequest {
    /// ID контента
    #[serde(rename = "content_id", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<i64>,
}

impl ContentDeleteRequest {
    pub fn new() -> ContentDeleteRequest {
        ContentDeleteRequest {
            content_id: None,
        }
    }
}

