/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// IllustrationResponse : Ответ содержит список URI адресов для контента, необходимый для метода [Инициализировать новый контент](./wbd#tag/Kontent/operation/contentUploadInit)
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IllustrationResponse {
    /// Список URI адресов обложки разного разрешения
    #[serde(rename = "uris")]
    pub uris: Vec<String>,
    /// ID пользователя
    #[serde(rename = "userId")]
    pub user_id: i64,
}

impl IllustrationResponse {
    /// Ответ содержит список URI адресов для контента, необходимый для метода [Инициализировать новый контент](./wbd#tag/Kontent/operation/contentUploadInit)
    pub fn new(uris: Vec<String>, user_id: i64) -> IllustrationResponse {
        IllustrationResponse {
            uris,
            user_id,
        }
    }
}

