/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyRedeemedResponse {
    /// ID ключа
    #[serde(rename = "id")]
    pub id: i64,
    /// Ключ
    #[serde(rename = "value")]
    pub value: String,
    /// Дата создания ключа
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Дата покупки ключа
    #[serde(rename = "buyed_at")]
    pub buyed_at: String,
    /// ID предложения
    #[serde(rename = "offer_id")]
    pub offer_id: i64,
    /// Название предложения
    #[serde(rename = "offer_title")]
    pub offer_title: String,
    /// Цена предложения
    #[serde(rename = "offer_price")]
    pub offer_price: i64,
}

impl KeyRedeemedResponse {
    pub fn new(id: i64, value: String, created_at: String, buyed_at: String, offer_id: i64, offer_title: String, offer_price: i64) -> KeyRedeemedResponse {
        KeyRedeemedResponse {
            id,
            value,
            created_at,
            buyed_at,
            offer_id,
            offer_title,
            offer_price,
        }
    }
}

