/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyResponse {
    /// ID ключа
    #[serde(rename = "id")]
    pub id: i64,
    /// Значение ключа
    #[serde(rename = "value")]
    pub value: String,
    /// Дата и время создания ключа
    #[serde(rename = "created_at")]
    pub created_at: String,
    /// Дата и время покупки ключа
    #[serde(rename = "buyed_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub buyed_at: Option<Option<String>>,
    /// Дата и время удаления ключа
    #[serde(rename = "deleted_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<Option<String>>,
}

impl KeyResponse {
    pub fn new(id: i64, value: String, created_at: String) -> KeyResponse {
        KeyResponse {
            id,
            value,
            created_at,
            buyed_at: None,
            deleted_at: None,
        }
    }
}

