/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysResponseList {
    /// Список ключей
    #[serde(rename = "items")]
    pub items: Vec<models::KeyResponse>,
    /// Общее количество ключей
    #[serde(rename = "total")]
    pub total: i64,
}

impl KeysResponseList {
    pub fn new(items: Vec<models::KeyResponse>, total: i64) -> KeysResponseList {
        KeysResponseList {
            items,
            total,
        }
    }
}

