/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysDeleteResponseStatusesInner {
    /// ID ключа
    #[serde(rename = "id")]
    pub id: i64,
    /// HTTP статус-код для каждой операции над ключом
    #[serde(rename = "code")]
    pub code: String,
    /// Описание к статусу удаления
    #[serde(rename = "message")]
    pub message: String,
    /// Флаг статуса удаления (`true` - успешно удален, `false` - ошибка)
    #[serde(rename = "status")]
    pub status: bool,
}

impl KeysDeleteResponseStatusesInner {
    pub fn new(id: i64, code: String, message: String, status: bool) -> KeysDeleteResponseStatusesInner {
        KeysDeleteResponseStatusesInner {
            id,
            code,
            message,
            status,
        }
    }
}

