/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KeysLoadRequest : Список ключей и ID предложения
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysLoadRequest {
    /// Список ключей.<br><br>  **Ограничения:** - Максимальное количество ключей — **1000** - Максимальная длина ключа — **200 символов** 
    #[serde(rename = "keys")]
    pub keys: Vec<String>,
    /// ID предложения
    #[serde(rename = "offer_id")]
    pub offer_id: i64,
}

impl KeysLoadRequest {
    /// Список ключей и ID предложения
    pub fn new(keys: Vec<String>, offer_id: i64) -> KeysLoadRequest {
        KeysLoadRequest {
            keys,
            offer_id,
        }
    }
}

