/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeysCountResponse {
    /// Общее количество ключей
    #[serde(rename = "total")]
    pub total: i64,
    /// Количество свободных ключей
    #[serde(rename = "available")]
    pub available: i64,
    /// Количество зарезервированных ключей
    #[serde(rename = "reserved")]
    pub reserved: i64,
    /// Количество удаленных ключей
    #[serde(rename = "deleted")]
    pub deleted: i64,
}

impl KeysCountResponse {
    pub fn new(total: i64, available: i64, reserved: i64, deleted: i64) -> KeysCountResponse {
        KeysCountResponse {
            total,
            available,
            reserved,
            deleted,
        }
    }
}

