/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferMetaRequest : Метаданные предложения
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferMetaRequest {
    /// Адреса где можно воспользоваться купонами, подарочными сертификатами
    #[serde(rename = "addresses", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub addresses: Option<Option<String>>,
    /// Инструкция по активации ключа
    #[serde(rename = "key_instruction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub key_instruction: Option<Option<String>>,
}

impl OfferMetaRequest {
    /// Метаданные предложения
    pub fn new() -> OfferMetaRequest {
        OfferMetaRequest {
            addresses: None,
            key_instruction: None,
        }
    }
}

