/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferCreateRequest : Новое предложение
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferCreateRequest {
    /// Название предложения.<br>Максимальная длина — **500 символов.**
    #[serde(rename = "title")]
    pub title: String,
    /// Описание предложения. Это текст, который описывает ваше предложение и помогает людям понять, что именно представляет из себя продаваемый вами товар и чем он может быть полезен. Важно правильно назвать предложение и более подробно прописать его описание, чтобы пользователи узнали как можно больше информации еще до покупки.<br>Максимальная длина — **5000 символов.**
    #[serde(rename = "description")]
    pub description: String,
    /// Массив тегов. Теги нужны для группирования, ранжирования и облегчения поиска вашего товара.<br><br>  **Ограничения**: - Максимальное количество тегов — **5** - Максимальная длина тега — **45 символов** 
    #[serde(rename = "tags")]
    pub tags: Vec<String>,
    /// ID категории предложения: - `1` — Видеоконтент - `2` — Аудиоконтент - `3` — Ключи активации - `4` — Электронные книги - `5` — Аудиокниги - `6` — Цифровые товары - `8` — Услуги - `12` — Купоны и развлечения - `13` — Подарочные сертификаты 
    #[serde(rename = "section")]
    pub section: Section,
    /// Массив ID подкатегорий, в котором находится предложение.<br> Воспользуйтесь методом [Получить категории и их подкатегории](./wbd#tag/Predlozheniya/operation/GetCatalog) для получения ID и правильного сопоставления с категорией. 
    #[serde(rename = "catalog_path")]
    pub catalog_path: Vec<i64>,
    /// Возрастное ограничение. Это система, которая используется для определения, подходит ли ваше предложение для определенной возрастной группы.
    #[serde(rename = "age_rating")]
    pub age_rating: AgeRating,
    /// Цена предложения, ₽
    #[serde(rename = "price")]
    pub price: i64,
    /// Цена с учетом скидки, ₽
    #[serde(rename = "discount_price", skip_serializing_if = "Option::is_none")]
    pub discount_price: Option<i64>,
    /// Список URL-адресов дополнительных изображений, а так же видео превью.<br> **Можно передать до 8 медиафайлов.**<br> **Важно, чтобы все изображения были в формате JPG или PNG, а видео в формате MP4** 
    #[serde(rename = "gallery", skip_serializing_if = "Option::is_none")]
    pub gallery: Option<Vec<String>>,
    /// Список ключей.<br> Это **обязательное поле**, если вы хотите создать предложение из категории (`section`): - **Ключи активации** — `3` - **Купоны и развлечения** — `12` - **Подарочные сертификаты** — `13`  **Ограничения:** - Максимальное количество ключей — **1000** - Максимальная длина ключа — **200 символов** 
    #[serde(rename = "keys", skip_serializing_if = "Option::is_none")]
    pub keys: Option<Vec<String>>,
    /// Задается статус вашего предложения: - `0` — Добавить в черновик - `1` — Опубликовать 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Список контента
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Vec<models::OfferCreateContent>>,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::OfferMetaRequest>>,
}

impl OfferCreateRequest {
    /// Новое предложение
    pub fn new(title: String, description: String, tags: Vec<String>, section: Section, catalog_path: Vec<i64>, age_rating: AgeRating, price: i64) -> OfferCreateRequest {
        OfferCreateRequest {
            title,
            description,
            tags,
            section,
            catalog_path,
            age_rating,
            price,
            discount_price: None,
            gallery: None,
            keys: None,
            status: None,
            content: None,
            meta: None,
        }
    }
}
/// ID категории предложения: - `1` — Видеоконтент - `2` — Аудиоконтент - `3` — Ключи активации - `4` — Электронные книги - `5` — Аудиокниги - `6` — Цифровые товары - `8` — Услуги - `12` — Купоны и развлечения - `13` — Подарочные сертификаты 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Section {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "4")]
    Variant4,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "6")]
    Variant6,
    #[serde(rename = "8")]
    Variant8,
    #[serde(rename = "9")]
    Variant9,
    #[serde(rename = "12")]
    Variant12,
    #[serde(rename = "13")]
    Variant13,
}

impl Default for Section {
    fn default() -> Section {
        Self::Variant1
    }
}
/// Возрастное ограничение. Это система, которая используется для определения, подходит ли ваше предложение для определенной возрастной группы.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgeRating {
    #[serde(rename = "0+")]
    Variant0Plus,
    #[serde(rename = "6+")]
    Variant6Plus,
    #[serde(rename = "12+")]
    Variant12Plus,
    #[serde(rename = "14+")]
    Variant14Plus,
    #[serde(rename = "16+")]
    Variant16Plus,
    #[serde(rename = "18+")]
    Variant18Plus,
}

impl Default for AgeRating {
    fn default() -> AgeRating {
        Self::Variant0Plus
    }
}
/// Задается статус вашего предложения: - `0` — Добавить в черновик - `1` — Опубликовать 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant0
    }
}

