/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferPriceUpdateRequest : Новая цена для предложения
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferPriceUpdateRequest {
    /// Цена, ₽
    #[serde(rename = "regular_price", skip_serializing_if = "Option::is_none")]
    pub regular_price: Option<i64>,
    /// Цена с учетом скидки, ₽
    #[serde(rename = "discount_price", skip_serializing_if = "Option::is_none")]
    pub discount_price: Option<i64>,
}

impl OfferPriceUpdateRequest {
    /// Новая цена для предложения
    pub fn new() -> OfferPriceUpdateRequest {
        OfferPriceUpdateRequest {
            regular_price: None,
            discount_price: None,
        }
    }
}

