/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferContent {
    /// ID контента
    #[serde(rename = "content")]
    pub content: i64,
    /// Название контента
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Описание контента
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Список с информацией о дополнительных файлах
    #[serde(rename = "files", skip_serializing_if = "Option::is_none")]
    pub files: Option<Vec<models::OfferContentFilesInner>>,
    /// Хранит в себе метаданные контента: - `bisac` —  ISBN (Международный стандартный книжный номер) - `voice` — Актер озвучивающий аудиоконтент - `author` — Автор контента - `rating` — Возрастное ограничение - `preview` — Короткий отрезок контента для предварительного просмотра - `duration` — Продолжительность контента - `thumbnail` — Список обложки для контента разного разрешения - `dimensions` — Список разрешений видео - `duration_ms` — Продолжительность контента в миллисекундах - `translator` — Автор перевода - `original_name` — Оригинальное название контента - `pages` — Количество страниц в контенте - `encoded_videos` — Список информации (размер, разрешение) для декодированного видео - `encoded_audios` — Список информации (размер, битрейт) для декодированного аудио 
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<String>,
    /// URI адрес на плейлист контента.<br><br>  Если контент является аудио или видео контентом, то файл декодируется в плейлист 
    #[serde(rename = "playlist", skip_serializing_if = "Option::is_none")]
    pub playlist: Option<String>,
    /// ID категории контента: - `1` — Видеоконтент - `2` — Аудиоконтент - `4` — Документ 
    #[serde(rename = "category_id", skip_serializing_if = "Option::is_none")]
    pub category_id: Option<CategoryId>,
}

impl OfferContent {
    pub fn new(content: i64) -> OfferContent {
        OfferContent {
            content,
            title: None,
            description: None,
            files: None,
            meta: None,
            playlist: None,
            category_id: None,
        }
    }
}
/// ID категории контента: - `1` — Видеоконтент - `2` — Аудиоконтент - `4` — Документ 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CategoryId {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "4")]
    Variant4,
}

impl Default for CategoryId {
    fn default() -> CategoryId {
        Self::Variant1
    }
}

