/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferCreateContent {
    /// ID категории контента: - `1` — Видео - `2` — Аудиоконтент - `4` — Документ 
    #[serde(rename = "category_id")]
    pub category_id: i64,
    /// ID контента
    #[serde(rename = "content")]
    pub content: i64,
}

impl OfferCreateContent {
    pub fn new(category_id: i64, content: i64) -> OfferCreateContent {
        OfferCreateContent {
            category_id,
            content,
        }
    }
}

