/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OfferStatusUpdateRequest : Новый статус
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OfferStatusUpdateRequest {
    #[serde(rename = "status")]
    pub status: Status,
}

impl OfferStatusUpdateRequest {
    /// Новый статус
    pub fn new(status: Status) -> OfferStatusUpdateRequest {
        OfferStatusUpdateRequest {
            status,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "0")]
    Variant0,
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for Status {
    fn default() -> Status {
        Self::Variant0
    }
}

