/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadChunkResponse : Файл успешно загружен.<br> Ответ содержит URI адрес контента 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadChunkResponse {
    /// Количество переданных фреймов (частей контента)
    #[serde(rename = "chunk", skip_serializing_if = "Option::is_none")]
    pub chunk: Option<i32>,
    /// URI адреса загруженного файла 
    #[serde(rename = "uri", skip_serializing_if = "Option::is_none")]
    pub uri: Option<String>,
}

impl UploadChunkResponse {
    /// Файл успешно загружен.<br> Ответ содержит URI адрес контента 
    pub fn new() -> UploadChunkResponse {
        UploadChunkResponse {
            chunk: None,
            uri: None,
        }
    }
}

