/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadGalleryResponse : Файлы успешно загружены.<br> Ответ содержит список URI адресов медиафайлов 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadGalleryResponse {
    /// Список URI адресов медиафайлов
    #[serde(rename = "uris", skip_serializing_if = "Option::is_none")]
    pub uris: Option<Vec<String>>,
}

impl UploadGalleryResponse {
    /// Файлы успешно загружены.<br> Ответ содержит список URI адресов медиафайлов 
    pub fn new() -> UploadGalleryResponse {
        UploadGalleryResponse {
            uris: None,
        }
    }
}

