/*
 * Wildberries Цифровой
 *
 * По вопросам работы с WBD API обращайтесь в <a href=\"https://digital.wildberries.ru/support\" target=\"_blank\">техническую поддержку</a> 
 *
 * The version of the OpenAPI document: wbd
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UploadInitResponse : Ответ. Содержит UUID контента, необходимый для метода [Загрузить контент (файл)](./wbd#tag/Kontent/operation/contentUploadChunk) 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadInitResponse {
    /// ID контента
    #[serde(rename = "content_id", skip_serializing_if = "Option::is_none")]
    pub content_id: Option<i64>,
    /// Уникальный ID. Этот ID необходим для загрузки самого файла в методе [Загрузка контента (файла)](./wbd#tag/Kontent/operation/contentUploadChunk) 
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,
}

impl UploadInitResponse {
    /// Ответ. Содержит UUID контента, необходимый для метода [Загрузить контент (файл)](./wbd#tag/Kontent/operation/contentUploadChunk) 
    pub fn new() -> UploadInitResponse {
        UploadInitResponse {
            content_id: None,
            uuid: None,
        }
    }
}

