/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonInfoAdvertisedProducts } from './CommonInfoAdvertisedProducts';
import {
    CommonInfoAdvertisedProductsFromJSON,
    CommonInfoAdvertisedProductsFromJSONTyped,
    CommonInfoAdvertisedProductsToJSON,
    CommonInfoAdvertisedProductsToJSONTyped,
} from './CommonInfoAdvertisedProducts';

/**
 * 
 * @export
 * @interface DistributionTableIndicators
 */
export interface DistributionTableIndicators {
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    feedbackCount?: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    fiveStar?: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    fourStar?: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    threeStar?: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    twoStar?: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof DistributionTableIndicators
     */
    oneStar?: CommonInfoAdvertisedProducts;
    /**
     * Отзывы, исключённые из рейтинга
     * @type {number}
     * @memberof DistributionTableIndicators
     */
    disqualified?: number;
}

/**
 * Check if a given object implements the DistributionTableIndicators interface.
 */
export function instanceOfDistributionTableIndicators(value: object): value is DistributionTableIndicators {
    return true;
}

export function DistributionTableIndicatorsFromJSON(json: any): DistributionTableIndicators {
    return DistributionTableIndicatorsFromJSONTyped(json, false);
}

export function DistributionTableIndicatorsFromJSONTyped(json: any, ignoreDiscriminator: boolean): DistributionTableIndicators {
    if (json == null) {
        return json;
    }
    return {
        
        'feedbackCount': json['feedbackCount'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['feedbackCount']),
        'fiveStar': json['fiveStar'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['fiveStar']),
        'fourStar': json['fourStar'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['fourStar']),
        'threeStar': json['threeStar'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['threeStar']),
        'twoStar': json['twoStar'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['twoStar']),
        'oneStar': json['oneStar'] == null ? undefined : CommonInfoAdvertisedProductsFromJSON(json['oneStar']),
        'disqualified': json['disqualified'] == null ? undefined : json['disqualified'],
    };
}

export function DistributionTableIndicatorsToJSON(json: any): DistributionTableIndicators {
    return DistributionTableIndicatorsToJSONTyped(json, false);
}

export function DistributionTableIndicatorsToJSONTyped(value?: DistributionTableIndicators | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'feedbackCount': CommonInfoAdvertisedProductsToJSON(value['feedbackCount']),
        'fiveStar': CommonInfoAdvertisedProductsToJSON(value['fiveStar']),
        'fourStar': CommonInfoAdvertisedProductsToJSON(value['fourStar']),
        'threeStar': CommonInfoAdvertisedProductsToJSON(value['threeStar']),
        'twoStar': CommonInfoAdvertisedProductsToJSON(value['twoStar']),
        'oneStar': CommonInfoAdvertisedProductsToJSON(value['oneStar']),
        'disqualified': value['disqualified'],
    };
}

