/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonInfoAdvertisedProducts } from './CommonInfoAdvertisedProducts';
import {
    CommonInfoAdvertisedProductsFromJSON,
    CommonInfoAdvertisedProductsFromJSONTyped,
    CommonInfoAdvertisedProductsToJSON,
    CommonInfoAdvertisedProductsToJSONTyped,
} from './CommonInfoAdvertisedProducts';

/**
 * Количество товаров со средней позицией в поиске:
 *   - `firstHundred` — от 1 до 100
 *   - `secondHundred` — от 101 до 200
 *   - `below` — от 201 и ниже
 * 
 * @export
 * @interface SearchReportPositionClusters
 */
export interface SearchReportPositionClusters {
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof SearchReportPositionClusters
     */
    firstHundred: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof SearchReportPositionClusters
     */
    secondHundred: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof SearchReportPositionClusters
     */
    below: CommonInfoAdvertisedProducts;
}

/**
 * Check if a given object implements the SearchReportPositionClusters interface.
 */
export function instanceOfSearchReportPositionClusters(value: object): value is SearchReportPositionClusters {
    if (!('firstHundred' in value) || value['firstHundred'] === undefined) return false;
    if (!('secondHundred' in value) || value['secondHundred'] === undefined) return false;
    if (!('below' in value) || value['below'] === undefined) return false;
    return true;
}

export function SearchReportPositionClustersFromJSON(json: any): SearchReportPositionClusters {
    return SearchReportPositionClustersFromJSONTyped(json, false);
}

export function SearchReportPositionClustersFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchReportPositionClusters {
    if (json == null) {
        return json;
    }
    return {
        
        'firstHundred': CommonInfoAdvertisedProductsFromJSON(json['firstHundred']),
        'secondHundred': CommonInfoAdvertisedProductsFromJSON(json['secondHundred']),
        'below': CommonInfoAdvertisedProductsFromJSON(json['below']),
    };
}

export function SearchReportPositionClustersToJSON(json: any): SearchReportPositionClusters {
    return SearchReportPositionClustersToJSONTyped(json, false);
}

export function SearchReportPositionClustersToJSONTyped(value?: SearchReportPositionClusters | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstHundred': CommonInfoAdvertisedProductsToJSON(value['firstHundred']),
        'secondHundred': CommonInfoAdvertisedProductsToJSON(value['secondHundred']),
        'below': CommonInfoAdvertisedProductsToJSON(value['below']),
    };
}

