/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonInfoAdvertisedProducts } from './CommonInfoAdvertisedProducts';
import {
    CommonInfoAdvertisedProductsFromJSON,
    CommonInfoAdvertisedProductsFromJSONTyped,
    CommonInfoAdvertisedProductsToJSON,
    CommonInfoAdvertisedProductsToJSONTyped,
} from './CommonInfoAdvertisedProducts';

/**
 * Метрики товара в таблице
 * @export
 * @interface TableGroupItemMetrics
 */
export interface TableGroupItemMetrics {
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    avgPosition: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    openCard: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    addToCart: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    openToCart: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    orders: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    cartToOrder: CommonInfoAdvertisedProducts;
    /**
     * 
     * @type {CommonInfoAdvertisedProducts}
     * @memberof TableGroupItemMetrics
     */
    visibility: CommonInfoAdvertisedProducts;
}

/**
 * Check if a given object implements the TableGroupItemMetrics interface.
 */
export function instanceOfTableGroupItemMetrics(value: object): value is TableGroupItemMetrics {
    if (!('avgPosition' in value) || value['avgPosition'] === undefined) return false;
    if (!('openCard' in value) || value['openCard'] === undefined) return false;
    if (!('addToCart' in value) || value['addToCart'] === undefined) return false;
    if (!('openToCart' in value) || value['openToCart'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('cartToOrder' in value) || value['cartToOrder'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function TableGroupItemMetricsFromJSON(json: any): TableGroupItemMetrics {
    return TableGroupItemMetricsFromJSONTyped(json, false);
}

export function TableGroupItemMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableGroupItemMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'avgPosition': CommonInfoAdvertisedProductsFromJSON(json['avgPosition']),
        'openCard': CommonInfoAdvertisedProductsFromJSON(json['openCard']),
        'addToCart': CommonInfoAdvertisedProductsFromJSON(json['addToCart']),
        'openToCart': CommonInfoAdvertisedProductsFromJSON(json['openToCart']),
        'orders': CommonInfoAdvertisedProductsFromJSON(json['orders']),
        'cartToOrder': CommonInfoAdvertisedProductsFromJSON(json['cartToOrder']),
        'visibility': CommonInfoAdvertisedProductsFromJSON(json['visibility']),
    };
}

export function TableGroupItemMetricsToJSON(json: any): TableGroupItemMetrics {
    return TableGroupItemMetricsToJSONTyped(json, false);
}

export function TableGroupItemMetricsToJSONTyped(value?: TableGroupItemMetrics | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avgPosition': CommonInfoAdvertisedProductsToJSON(value['avgPosition']),
        'openCard': CommonInfoAdvertisedProductsToJSON(value['openCard']),
        'addToCart': CommonInfoAdvertisedProductsToJSON(value['addToCart']),
        'openToCart': CommonInfoAdvertisedProductsToJSON(value['openToCart']),
        'orders': CommonInfoAdvertisedProductsToJSON(value['orders']),
        'cartToOrder': CommonInfoAdvertisedProductsToJSON(value['cartToOrder']),
        'visibility': CommonInfoAdvertisedProductsToJSON(value['visibility']),
    };
}

