/* tslint:disable */
/* eslint-disable */
/**
 * Аналитика и данные
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableProductItemAllOfPrice } from './TableProductItemAllOfPrice';
import {
    TableProductItemAllOfPriceFromJSON,
    TableProductItemAllOfPriceFromJSONTyped,
    TableProductItemAllOfPriceToJSON,
    TableProductItemAllOfPriceToJSONTyped,
} from './TableProductItemAllOfPrice';
import type { TableProductItemAllOfAvgPosition } from './TableProductItemAllOfAvgPosition';
import {
    TableProductItemAllOfAvgPositionFromJSON,
    TableProductItemAllOfAvgPositionFromJSONTyped,
    TableProductItemAllOfAvgPositionToJSON,
    TableProductItemAllOfAvgPositionToJSONTyped,
} from './TableProductItemAllOfAvgPosition';

/**
 * 
 * @export
 * @interface TableProductItem
 */
export interface TableProductItem {
    /**
     * Артикул WB
     * @type {number}
     * @memberof TableProductItem
     */
    nmId: number;
    /**
     * Название товара
     * @type {string}
     * @memberof TableProductItem
     */
    name?: string;
    /**
     * Артикул продавца
     * @type {string}
     * @memberof TableProductItem
     */
    vendorCode: string;
    /**
     * Название предмета
     * @type {string}
     * @memberof TableProductItem
     */
    subjectName?: string;
    /**
     * Бренд
     * @type {string}
     * @memberof TableProductItem
     */
    brandName?: string;
    /**
     * URL главного фото карточки товара
     * @type {string}
     * @memberof TableProductItem
     */
    mainPhoto?: string;
    /**
     * Находится ли товар в продвижении в Поисковой выдаче
     * @type {boolean}
     * @memberof TableProductItem
     */
    isAdvertised: boolean;
    /**
     * Искали ли товар по подменному артикулу.<br>
     * Поле будет в ответе при наличии в запросе `includeSubstitutedSKUs` и/или `includeSearchTexts`
     * 
     * @type {boolean}
     * @memberof TableProductItem
     */
    isSubstitutedSKU?: boolean;
    /**
     * Есть ли рейтинг у карточки товара
     * @type {boolean}
     * @memberof TableProductItem
     */
    isCardRated: boolean;
    /**
     * Рейтинг карточки товара
     * @type {number}
     * @memberof TableProductItem
     */
    rating: number;
    /**
     * Рейтинг по отзывам
     * @type {number}
     * @memberof TableProductItem
     */
    feedbackRating: number;
    /**
     * 
     * @type {TableProductItemAllOfPrice}
     * @memberof TableProductItem
     */
    price: TableProductItemAllOfPrice;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    avgPosition: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    openCard: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    addToCart: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    openToCart: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    orders: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    cartToOrder: TableProductItemAllOfAvgPosition;
    /**
     * 
     * @type {TableProductItemAllOfAvgPosition}
     * @memberof TableProductItem
     */
    visibility: TableProductItemAllOfAvgPosition;
}

/**
 * Check if a given object implements the TableProductItem interface.
 */
export function instanceOfTableProductItem(value: object): value is TableProductItem {
    if (!('nmId' in value) || value['nmId'] === undefined) return false;
    if (!('vendorCode' in value) || value['vendorCode'] === undefined) return false;
    if (!('isAdvertised' in value) || value['isAdvertised'] === undefined) return false;
    if (!('isCardRated' in value) || value['isCardRated'] === undefined) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('feedbackRating' in value) || value['feedbackRating'] === undefined) return false;
    if (!('price' in value) || value['price'] === undefined) return false;
    if (!('avgPosition' in value) || value['avgPosition'] === undefined) return false;
    if (!('openCard' in value) || value['openCard'] === undefined) return false;
    if (!('addToCart' in value) || value['addToCart'] === undefined) return false;
    if (!('openToCart' in value) || value['openToCart'] === undefined) return false;
    if (!('orders' in value) || value['orders'] === undefined) return false;
    if (!('cartToOrder' in value) || value['cartToOrder'] === undefined) return false;
    if (!('visibility' in value) || value['visibility'] === undefined) return false;
    return true;
}

export function TableProductItemFromJSON(json: any): TableProductItem {
    return TableProductItemFromJSONTyped(json, false);
}

export function TableProductItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableProductItem {
    if (json == null) {
        return json;
    }
    return {
        
        'nmId': json['nmId'],
        'name': json['name'] == null ? undefined : json['name'],
        'vendorCode': json['vendorCode'],
        'subjectName': json['subjectName'] == null ? undefined : json['subjectName'],
        'brandName': json['brandName'] == null ? undefined : json['brandName'],
        'mainPhoto': json['mainPhoto'] == null ? undefined : json['mainPhoto'],
        'isAdvertised': json['isAdvertised'],
        'isSubstitutedSKU': json['isSubstitutedSKU'] == null ? undefined : json['isSubstitutedSKU'],
        'isCardRated': json['isCardRated'],
        'rating': json['rating'],
        'feedbackRating': json['feedbackRating'],
        'price': TableProductItemAllOfPriceFromJSON(json['price']),
        'avgPosition': TableProductItemAllOfAvgPositionFromJSON(json['avgPosition']),
        'openCard': TableProductItemAllOfAvgPositionFromJSON(json['openCard']),
        'addToCart': TableProductItemAllOfAvgPositionFromJSON(json['addToCart']),
        'openToCart': TableProductItemAllOfAvgPositionFromJSON(json['openToCart']),
        'orders': TableProductItemAllOfAvgPositionFromJSON(json['orders']),
        'cartToOrder': TableProductItemAllOfAvgPositionFromJSON(json['cartToOrder']),
        'visibility': TableProductItemAllOfAvgPositionFromJSON(json['visibility']),
    };
}

export function TableProductItemToJSON(json: any): TableProductItem {
    return TableProductItemToJSONTyped(json, false);
}

export function TableProductItemToJSONTyped(value?: TableProductItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nmId': value['nmId'],
        'name': value['name'],
        'vendorCode': value['vendorCode'],
        'subjectName': value['subjectName'],
        'brandName': value['brandName'],
        'mainPhoto': value['mainPhoto'],
        'isAdvertised': value['isAdvertised'],
        'isSubstitutedSKU': value['isSubstitutedSKU'],
        'isCardRated': value['isCardRated'],
        'rating': value['rating'],
        'feedbackRating': value['feedbackRating'],
        'price': TableProductItemAllOfPriceToJSON(value['price']),
        'avgPosition': TableProductItemAllOfAvgPositionToJSON(value['avgPosition']),
        'openCard': TableProductItemAllOfAvgPositionToJSON(value['openCard']),
        'addToCart': TableProductItemAllOfAvgPositionToJSON(value['addToCart']),
        'openToCart': TableProductItemAllOfAvgPositionToJSON(value['openToCart']),
        'orders': TableProductItemAllOfAvgPositionToJSON(value['orders']),
        'cartToOrder': TableProductItemAllOfAvgPositionToJSON(value['cartToOrder']),
        'visibility': TableProductItemAllOfAvgPositionToJSON(value['visibility']),
    };
}

