/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Response208SetRecom
 */
export interface Response208SetRecom {
    /**
     * ID запроса
     * @type {string}
     * @memberof Response208SetRecom
     */
    requestId: string;
    /**
     * ID внутреннего сервиса WB
     * @type {string}
     * @memberof Response208SetRecom
     */
    origin: string;
    /**
     * Заголовок ответа
     * @type {string}
     * @memberof Response208SetRecom
     */
    title: string;
    /**
     * Детали ответа
     * @type {string}
     * @memberof Response208SetRecom
     */
    detail: string;
}

/**
 * Check if a given object implements the Response208SetRecom interface.
 */
export function instanceOfResponse208SetRecom(value: object): value is Response208SetRecom {
    if (!('requestId' in value) || value['requestId'] === undefined) return false;
    if (!('origin' in value) || value['origin'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function Response208SetRecomFromJSON(json: any): Response208SetRecom {
    return Response208SetRecomFromJSONTyped(json, false);
}

export function Response208SetRecomFromJSONTyped(json: any, ignoreDiscriminator: boolean): Response208SetRecom {
    if (json == null) {
        return json;
    }
    return {
        
        'requestId': json['requestId'],
        'origin': json['origin'],
        'title': json['title'],
        'detail': json['detail'],
    };
}

export function Response208SetRecomToJSON(json: any): Response208SetRecom {
    return Response208SetRecomToJSONTyped(json, false);
}

export function Response208SetRecomToJSONTyped(value?: Response208SetRecom | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'requestId': value['requestId'],
        'origin': value['origin'],
        'title': value['title'],
        'detail': value['detail'],
    };
}

