/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetRecomResErrorsInner } from './SetRecomResErrorsInner';
import {
    SetRecomResErrorsInnerFromJSON,
    SetRecomResErrorsInnerFromJSONTyped,
    SetRecomResErrorsInnerToJSON,
    SetRecomResErrorsInnerToJSONTyped,
} from './SetRecomResErrorsInner';

/**
 * 
 * @export
 * @interface SetRecomRes
 */
export interface SetRecomRes {
    /**
     * Есть ли ошибки:
     *   - `false` — ошибок нет. Запрос полностью успешен
     *   - `true` — ошибки есть
     * 
     * @type {boolean}
     * @memberof SetRecomRes
     */
    isError: boolean;
    /**
     * Ошибки. При `"isError":true`
     * @type {Array<SetRecomResErrorsInner>}
     * @memberof SetRecomRes
     */
    errors?: Array<SetRecomResErrorsInner>;
}

/**
 * Check if a given object implements the SetRecomRes interface.
 */
export function instanceOfSetRecomRes(value: object): value is SetRecomRes {
    if (!('isError' in value) || value['isError'] === undefined) return false;
    return true;
}

export function SetRecomResFromJSON(json: any): SetRecomRes {
    return SetRecomResFromJSONTyped(json, false);
}

export function SetRecomResFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRecomRes {
    if (json == null) {
        return json;
    }
    return {
        
        'isError': json['isError'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(SetRecomResErrorsInnerFromJSON)),
    };
}

export function SetRecomResToJSON(json: any): SetRecomRes {
    return SetRecomResToJSONTyped(json, false);
}

export function SetRecomResToJSONTyped(value?: SetRecomRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'isError': value['isError'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(SetRecomResErrorsInnerToJSON)),
    };
}

