/* tslint:disable */
/* eslint-disable */
/**
 * Маркетинг и продвижение
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SetRecomReqRecListInner } from './SetRecomReqRecListInner';
import {
    SetRecomReqRecListInnerFromJSON,
    SetRecomReqRecListInnerFromJSONTyped,
    SetRecomReqRecListInnerToJSON,
    SetRecomReqRecListInnerToJSONTyped,
} from './SetRecomReqRecListInner';

/**
 * Запрос на добавление или замену рекомендаций
 * @export
 * @interface SetRecomReq
 */
export interface SetRecomReq {
    /**
     * Список рекомендаций для товаров
     * @type {Array<SetRecomReqRecListInner>}
     * @memberof SetRecomReq
     */
    recList: Array<SetRecomReqRecListInner>;
    /**
     * Действие в запросе:
     *   - `false` — добавить новые рекомендации к существующим
     *   - `true` — заменить существующие рекомендации новыми
     * 
     * @type {boolean}
     * @memberof SetRecomReq
     */
    replace?: boolean;
}

/**
 * Check if a given object implements the SetRecomReq interface.
 */
export function instanceOfSetRecomReq(value: object): value is SetRecomReq {
    if (!('recList' in value) || value['recList'] === undefined) return false;
    return true;
}

export function SetRecomReqFromJSON(json: any): SetRecomReq {
    return SetRecomReqFromJSONTyped(json, false);
}

export function SetRecomReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRecomReq {
    if (json == null) {
        return json;
    }
    return {
        
        'recList': ((json['recList'] as Array<any>).map(SetRecomReqRecListInnerFromJSON)),
        'replace': json['replace'] == null ? undefined : json['replace'],
    };
}

export function SetRecomReqToJSON(json: any): SetRecomReq {
    return SetRecomReqToJSONTyped(json, false);
}

export function SetRecomReqToJSONTyped(value?: SetRecomReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recList': ((value['recList'] as Array<any>).map(SetRecomReqRecListInnerToJSON)),
        'replace': value['replace'],
    };
}

