/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the GetRecomReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRecomReq{}

// GetRecomReq Запрос для получения рекомендаций
type GetRecomReq struct {
	// Бренды
	BrandNames []string `json:"brandNames,omitempty"`
	// Количество товаров в ответе
	Limit *int32 `json:"limit,omitempty"`
	// Курсор. Последний `nmId` в ответе
	Next *int32 `json:"next,omitempty"`
	// Поиск:   - по артикулу WB `nmId` — полное совпадение   - по артикулу продавца `vendorCode` — частичное совпадение 
	Search *string `json:"search,omitempty"`
	// ID предметов
	SubjectIds []int32 `json:"subjectIds,omitempty"`
}

// NewGetRecomReq instantiates a new GetRecomReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRecomReq() *GetRecomReq {
	this := GetRecomReq{}
	var limit int32 = 20
	this.Limit = &limit
	var next int32 = 0
	this.Next = &next
	return &this
}

// NewGetRecomReqWithDefaults instantiates a new GetRecomReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRecomReqWithDefaults() *GetRecomReq {
	this := GetRecomReq{}
	var limit int32 = 20
	this.Limit = &limit
	var next int32 = 0
	this.Next = &next
	return &this
}

// GetBrandNames returns the BrandNames field value if set, zero value otherwise.
func (o *GetRecomReq) GetBrandNames() []string {
	if o == nil || IsNil(o.BrandNames) {
		var ret []string
		return ret
	}
	return o.BrandNames
}

// GetBrandNamesOk returns a tuple with the BrandNames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecomReq) GetBrandNamesOk() ([]string, bool) {
	if o == nil || IsNil(o.BrandNames) {
		return nil, false
	}
	return o.BrandNames, true
}

// HasBrandNames returns a boolean if a field has been set.
func (o *GetRecomReq) HasBrandNames() bool {
	if o != nil && !IsNil(o.BrandNames) {
		return true
	}

	return false
}

// SetBrandNames gets a reference to the given []string and assigns it to the BrandNames field.
func (o *GetRecomReq) SetBrandNames(v []string) {
	o.BrandNames = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetRecomReq) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecomReq) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetRecomReq) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetRecomReq) SetLimit(v int32) {
	o.Limit = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *GetRecomReq) GetNext() int32 {
	if o == nil || IsNil(o.Next) {
		var ret int32
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecomReq) GetNextOk() (*int32, bool) {
	if o == nil || IsNil(o.Next) {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *GetRecomReq) HasNext() bool {
	if o != nil && !IsNil(o.Next) {
		return true
	}

	return false
}

// SetNext gets a reference to the given int32 and assigns it to the Next field.
func (o *GetRecomReq) SetNext(v int32) {
	o.Next = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetRecomReq) GetSearch() string {
	if o == nil || IsNil(o.Search) {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecomReq) GetSearchOk() (*string, bool) {
	if o == nil || IsNil(o.Search) {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetRecomReq) HasSearch() bool {
	if o != nil && !IsNil(o.Search) {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetRecomReq) SetSearch(v string) {
	o.Search = &v
}

// GetSubjectIds returns the SubjectIds field value if set, zero value otherwise.
func (o *GetRecomReq) GetSubjectIds() []int32 {
	if o == nil || IsNil(o.SubjectIds) {
		var ret []int32
		return ret
	}
	return o.SubjectIds
}

// GetSubjectIdsOk returns a tuple with the SubjectIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRecomReq) GetSubjectIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.SubjectIds) {
		return nil, false
	}
	return o.SubjectIds, true
}

// HasSubjectIds returns a boolean if a field has been set.
func (o *GetRecomReq) HasSubjectIds() bool {
	if o != nil && !IsNil(o.SubjectIds) {
		return true
	}

	return false
}

// SetSubjectIds gets a reference to the given []int32 and assigns it to the SubjectIds field.
func (o *GetRecomReq) SetSubjectIds(v []int32) {
	o.SubjectIds = v
}

func (o GetRecomReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRecomReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrandNames) {
		toSerialize["brandNames"] = o.BrandNames
	}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Next) {
		toSerialize["next"] = o.Next
	}
	if !IsNil(o.Search) {
		toSerialize["search"] = o.Search
	}
	if !IsNil(o.SubjectIds) {
		toSerialize["subjectIds"] = o.SubjectIds
	}
	return toSerialize, nil
}

type NullableGetRecomReq struct {
	value *GetRecomReq
	isSet bool
}

func (v NullableGetRecomReq) Get() *GetRecomReq {
	return v.value
}

func (v *NullableGetRecomReq) Set(val *GetRecomReq) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRecomReq) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRecomReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRecomReq(val *GetRecomReq) *NullableGetRecomReq {
	return &NullableGetRecomReq{value: val, isSet: true}
}

func (v NullableGetRecomReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRecomReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


