/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetRecomReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetRecomReq{}

// SetRecomReq Запрос на добавление или замену рекомендаций
type SetRecomReq struct {
	// Список рекомендаций для товаров
	RecList []SetRecomReqRecListInner `json:"recList"`
	// Действие в запросе:   - `false` — добавить новые рекомендации к существующим   - `true` — заменить существующие рекомендации новыми 
	Replace *bool `json:"replace,omitempty"`
}

type _SetRecomReq SetRecomReq

// NewSetRecomReq instantiates a new SetRecomReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetRecomReq(recList []SetRecomReqRecListInner) *SetRecomReq {
	this := SetRecomReq{}
	this.RecList = recList
	var replace bool = false
	this.Replace = &replace
	return &this
}

// NewSetRecomReqWithDefaults instantiates a new SetRecomReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetRecomReqWithDefaults() *SetRecomReq {
	this := SetRecomReq{}
	var replace bool = false
	this.Replace = &replace
	return &this
}

// GetRecList returns the RecList field value
func (o *SetRecomReq) GetRecList() []SetRecomReqRecListInner {
	if o == nil {
		var ret []SetRecomReqRecListInner
		return ret
	}

	return o.RecList
}

// GetRecListOk returns a tuple with the RecList field value
// and a boolean to check if the value has been set.
func (o *SetRecomReq) GetRecListOk() ([]SetRecomReqRecListInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecList, true
}

// SetRecList sets field value
func (o *SetRecomReq) SetRecList(v []SetRecomReqRecListInner) {
	o.RecList = v
}

// GetReplace returns the Replace field value if set, zero value otherwise.
func (o *SetRecomReq) GetReplace() bool {
	if o == nil || IsNil(o.Replace) {
		var ret bool
		return ret
	}
	return *o.Replace
}

// GetReplaceOk returns a tuple with the Replace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecomReq) GetReplaceOk() (*bool, bool) {
	if o == nil || IsNil(o.Replace) {
		return nil, false
	}
	return o.Replace, true
}

// HasReplace returns a boolean if a field has been set.
func (o *SetRecomReq) HasReplace() bool {
	if o != nil && !IsNil(o.Replace) {
		return true
	}

	return false
}

// SetReplace gets a reference to the given bool and assigns it to the Replace field.
func (o *SetRecomReq) SetReplace(v bool) {
	o.Replace = &v
}

func (o SetRecomReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetRecomReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["recList"] = o.RecList
	if !IsNil(o.Replace) {
		toSerialize["replace"] = o.Replace
	}
	return toSerialize, nil
}

func (o *SetRecomReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recList",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetRecomReq := _SetRecomReq{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetRecomReq)

	if err != nil {
		return err
	}

	*o = SetRecomReq(varSetRecomReq)

	return err
}

type NullableSetRecomReq struct {
	value *SetRecomReq
	isSet bool
}

func (v NullableSetRecomReq) Get() *SetRecomReq {
	return v.value
}

func (v *NullableSetRecomReq) Set(val *SetRecomReq) {
	v.value = val
	v.isSet = true
}

func (v NullableSetRecomReq) IsSet() bool {
	return v.isSet
}

func (v *NullableSetRecomReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetRecomReq(val *SetRecomReq) *NullableSetRecomReq {
	return &NullableSetRecomReq{value: val, isSet: true}
}

func (v NullableSetRecomReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetRecomReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


