/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
)

// checks if the SetRecomReqRecListInnerRecommendationsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetRecomReqRecListInnerRecommendationsInner{}

// SetRecomReqRecListInnerRecommendationsInner struct for SetRecomReqRecListInnerRecommendationsInner
type SetRecomReqRecListInnerRecommendationsInner struct {
	// Артикул WB рекомендуемого товара
	RecomNm *int32 `json:"recomNm,omitempty"`
	// На каком месте находится товар в списке рекомендаций
	Sort *int32 `json:"sort,omitempty"`
}

// NewSetRecomReqRecListInnerRecommendationsInner instantiates a new SetRecomReqRecListInnerRecommendationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetRecomReqRecListInnerRecommendationsInner() *SetRecomReqRecListInnerRecommendationsInner {
	this := SetRecomReqRecListInnerRecommendationsInner{}
	var recomNm int32 = 0
	this.RecomNm = &recomNm
	var sort int32 = 20
	this.Sort = &sort
	return &this
}

// NewSetRecomReqRecListInnerRecommendationsInnerWithDefaults instantiates a new SetRecomReqRecListInnerRecommendationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetRecomReqRecListInnerRecommendationsInnerWithDefaults() *SetRecomReqRecListInnerRecommendationsInner {
	this := SetRecomReqRecListInnerRecommendationsInner{}
	var recomNm int32 = 0
	this.RecomNm = &recomNm
	var sort int32 = 20
	this.Sort = &sort
	return &this
}

// GetRecomNm returns the RecomNm field value if set, zero value otherwise.
func (o *SetRecomReqRecListInnerRecommendationsInner) GetRecomNm() int32 {
	if o == nil || IsNil(o.RecomNm) {
		var ret int32
		return ret
	}
	return *o.RecomNm
}

// GetRecomNmOk returns a tuple with the RecomNm field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecomReqRecListInnerRecommendationsInner) GetRecomNmOk() (*int32, bool) {
	if o == nil || IsNil(o.RecomNm) {
		return nil, false
	}
	return o.RecomNm, true
}

// HasRecomNm returns a boolean if a field has been set.
func (o *SetRecomReqRecListInnerRecommendationsInner) HasRecomNm() bool {
	if o != nil && !IsNil(o.RecomNm) {
		return true
	}

	return false
}

// SetRecomNm gets a reference to the given int32 and assigns it to the RecomNm field.
func (o *SetRecomReqRecListInnerRecommendationsInner) SetRecomNm(v int32) {
	o.RecomNm = &v
}

// GetSort returns the Sort field value if set, zero value otherwise.
func (o *SetRecomReqRecListInnerRecommendationsInner) GetSort() int32 {
	if o == nil || IsNil(o.Sort) {
		var ret int32
		return ret
	}
	return *o.Sort
}

// GetSortOk returns a tuple with the Sort field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetRecomReqRecListInnerRecommendationsInner) GetSortOk() (*int32, bool) {
	if o == nil || IsNil(o.Sort) {
		return nil, false
	}
	return o.Sort, true
}

// HasSort returns a boolean if a field has been set.
func (o *SetRecomReqRecListInnerRecommendationsInner) HasSort() bool {
	if o != nil && !IsNil(o.Sort) {
		return true
	}

	return false
}

// SetSort gets a reference to the given int32 and assigns it to the Sort field.
func (o *SetRecomReqRecListInnerRecommendationsInner) SetSort(v int32) {
	o.Sort = &v
}

func (o SetRecomReqRecListInnerRecommendationsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetRecomReqRecListInnerRecommendationsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecomNm) {
		toSerialize["recomNm"] = o.RecomNm
	}
	if !IsNil(o.Sort) {
		toSerialize["sort"] = o.Sort
	}
	return toSerialize, nil
}

type NullableSetRecomReqRecListInnerRecommendationsInner struct {
	value *SetRecomReqRecListInnerRecommendationsInner
	isSet bool
}

func (v NullableSetRecomReqRecListInnerRecommendationsInner) Get() *SetRecomReqRecListInnerRecommendationsInner {
	return v.value
}

func (v *NullableSetRecomReqRecListInnerRecommendationsInner) Set(val *SetRecomReqRecListInnerRecommendationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableSetRecomReqRecListInnerRecommendationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableSetRecomReqRecListInnerRecommendationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetRecomReqRecListInnerRecommendationsInner(val *SetRecomReqRecListInnerRecommendationsInner) *NullableSetRecomReqRecListInnerRecommendationsInner {
	return &NullableSetRecomReqRecListInnerRecommendationsInner{value: val, isSet: true}
}

func (v NullableSetRecomReqRecListInnerRecommendationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetRecomReqRecListInnerRecommendationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


