/*
Маркетинг и продвижение

<div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 

API version: promotion
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package promotion

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRecomRes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRecomRes{}

// GetRecomRes Товары с рекомендациями
type GetRecomRes struct {
	// Данные о товарах и их рекомендациях
	Data []GetRecomResDataInner `json:"data"`
	// Курсор. Последний `nmId` в ответе
	Next int32 `json:"next"`
}

type _GetRecomRes GetRecomRes

// NewGetRecomRes instantiates a new GetRecomRes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRecomRes(data []GetRecomResDataInner, next int32) *GetRecomRes {
	this := GetRecomRes{}
	this.Data = data
	this.Next = next
	return &this
}

// NewGetRecomResWithDefaults instantiates a new GetRecomRes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRecomResWithDefaults() *GetRecomRes {
	this := GetRecomRes{}
	return &this
}

// GetData returns the Data field value
func (o *GetRecomRes) GetData() []GetRecomResDataInner {
	if o == nil {
		var ret []GetRecomResDataInner
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetRecomRes) GetDataOk() ([]GetRecomResDataInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *GetRecomRes) SetData(v []GetRecomResDataInner) {
	o.Data = v
}

// GetNext returns the Next field value
func (o *GetRecomRes) GetNext() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Next
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
func (o *GetRecomRes) GetNextOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Next, true
}

// SetNext sets field value
func (o *GetRecomRes) SetNext(v int32) {
	o.Next = v
}

func (o GetRecomRes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRecomRes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["next"] = o.Next
	return toSerialize, nil
}

func (o *GetRecomRes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"next",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRecomRes := _GetRecomRes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRecomRes)

	if err != nil {
		return err
	}

	*o = GetRecomRes(varGetRecomRes)

	return err
}

type NullableGetRecomRes struct {
	value *GetRecomRes
	isSet bool
}

func (v NullableGetRecomRes) Get() *GetRecomRes {
	return v.value
}

func (v *NullableGetRecomRes) Set(val *GetRecomRes) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRecomRes) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRecomRes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRecomRes(val *GetRecomRes) *NullableGetRecomRes {
	return &NullableGetRecomRes{value: val, isSet: true}
}

func (v NullableGetRecomRes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRecomRes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


