/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">     Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInner } from './ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInner';
import {
    ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerFromJSON,
    ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerFromJSONTyped,
    ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerToJSON,
    ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerToJSONTyped,
} from './ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInner';

/**
 * 
 * @export
 * @interface ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest
 */
export interface ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest {
    /**
     * 
     * @type {Array<ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInner>}
     * @memberof ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest
     */
    orders?: Array<ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInner>;
}

/**
 * Check if a given object implements the ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest interface.
 */
export function instanceOfApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest(value: object): value is ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest {
    return true;
}

export function ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestFromJSON(json: any): ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest {
    return ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestFromJSONTyped(json, false);
}

export function ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'orders': json['orders'] == null ? undefined : ((json['orders'] as Array<any>).map(ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerFromJSON)),
    };
}

export function ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestToJSON(json: any): ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest {
    return ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestToJSONTyped(json, false);
}

export function ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestToJSONTyped(value?: ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orders': value['orders'] == null ? undefined : ((value['orders'] as Array<any>).map(ApiMarketplaceV3DbsMetaCustomsDeclarationPostRequestOrdersInnerToJSON)),
    };
}

