/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">     Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3DbsOrdersNewGet402Response
 */
export interface ApiV3DbsOrdersNewGet402Response {
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof ApiV3DbsOrdersNewGet402Response
     */
    title?: string;
    /**
     * Детали ошибки. Ошибка означает, что на балансе сервиса из [Каталога](https://dev.wildberries.ru/business-solutions) недостаточно средств
     * @type {string}
     * @memberof ApiV3DbsOrdersNewGet402Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the ApiV3DbsOrdersNewGet402Response interface.
 */
export function instanceOfApiV3DbsOrdersNewGet402Response(value: object): value is ApiV3DbsOrdersNewGet402Response {
    return true;
}

export function ApiV3DbsOrdersNewGet402ResponseFromJSON(json: any): ApiV3DbsOrdersNewGet402Response {
    return ApiV3DbsOrdersNewGet402ResponseFromJSONTyped(json, false);
}

export function ApiV3DbsOrdersNewGet402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbsOrdersNewGet402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ApiV3DbsOrdersNewGet402ResponseToJSON(json: any): ApiV3DbsOrdersNewGet402Response {
    return ApiV3DbsOrdersNewGet402ResponseToJSONTyped(json, false);
}

export function ApiV3DbsOrdersNewGet402ResponseToJSONTyped(value?: ApiV3DbsOrdersNewGet402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
    };
}

