/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBS
 * <div class=\"description_important\">   Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Номер грузовой таможенной декларации
 * @export
 * @interface MetaCustomsDeclaration
 */
export interface MetaCustomsDeclaration {
    /**
     * 
     * @type {string}
     * @memberof MetaCustomsDeclaration
     */
    value?: string | null;
}

/**
 * Check if a given object implements the MetaCustomsDeclaration interface.
 */
export function instanceOfMetaCustomsDeclaration(value: object): value is MetaCustomsDeclaration {
    return true;
}

export function MetaCustomsDeclarationFromJSON(json: any): MetaCustomsDeclaration {
    return MetaCustomsDeclarationFromJSONTyped(json, false);
}

export function MetaCustomsDeclarationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaCustomsDeclaration {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetaCustomsDeclarationToJSON(json: any): MetaCustomsDeclaration {
    return MetaCustomsDeclarationToJSONTyped(json, false);
}

export function MetaCustomsDeclarationToJSONTyped(value?: MetaCustomsDeclaration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

