/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV) 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PastPeriod : Прошлый период для сравнения. Количество дней — меньше или равно `currentPeriod`
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PastPeriod {
    /// Дата начала периода. Не позднее `end`. Не ранее 365 суток от сегодня
    #[serde(rename = "start")]
    pub start: String,
    /// Дата окончания периода. Не позднее даты перед датой начала `currentPeriod`. Не ранее 365 суток от сегодня
    #[serde(rename = "end")]
    pub end: String,
}

impl PastPeriod {
    /// Прошлый период для сравнения. Количество дней — меньше или равно `currentPeriod`
    pub fn new(start: String, end: String) -> PastPeriod {
        PastPeriod {
            start,
            end,
        }
    }
}

