/*
 * Аналитика и данные
 *
 * <div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 
 *
 * The version of the OpenAPI document: analytics
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TableGroupItemMetrics : Метрики товара в таблице
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TableGroupItemMetrics {
    #[serde(rename = "avgPosition")]
    pub avg_position: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "openCard")]
    pub open_card: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "addToCart")]
    pub add_to_cart: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "openToCart")]
    pub open_to_cart: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "orders")]
    pub orders: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "cartToOrder")]
    pub cart_to_order: Box<models::CommonInfoAdvertisedProducts>,
    #[serde(rename = "visibility")]
    pub visibility: Box<models::CommonInfoAdvertisedProducts>,
}

impl TableGroupItemMetrics {
    /// Метрики товара в таблице
    pub fn new(avg_position: models::CommonInfoAdvertisedProducts, open_card: models::CommonInfoAdvertisedProducts, add_to_cart: models::CommonInfoAdvertisedProducts, open_to_cart: models::CommonInfoAdvertisedProducts, orders: models::CommonInfoAdvertisedProducts, cart_to_order: models::CommonInfoAdvertisedProducts, visibility: models::CommonInfoAdvertisedProducts) -> TableGroupItemMetrics {
        TableGroupItemMetrics {
            avg_position: Box::new(avg_position),
            open_card: Box::new(open_card),
            add_to_cart: Box::new(add_to_cart),
            open_to_cart: Box::new(open_to_cart),
            orders: Box::new(orders),
            cart_to_order: Box::new(cart_to_order),
            visibility: Box::new(visibility),
        }
    }
}

