/*
 * Заказы DBS
 *
 * <div class=\"description_important\">     Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbsOrdersStatusPost200ResponseOrdersInner {
    /// ID сборочного задания
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Статус сборочного задания, установленный продавцом
    #[serde(rename = "supplierStatus", skip_serializing_if = "Option::is_none")]
    pub supplier_status: Option<String>,
    /// Статус сборочного задания в системе Wildberries
    #[serde(rename = "wbStatus", skip_serializing_if = "Option::is_none")]
    pub wb_status: Option<String>,
}

impl ApiV3DbsOrdersStatusPost200ResponseOrdersInner {
    pub fn new() -> ApiV3DbsOrdersStatusPost200ResponseOrdersInner {
        ApiV3DbsOrdersStatusPost200ResponseOrdersInner {
            id: None,
            supplier_status: None,
            wb_status: None,
        }
    }
}

