/*
 * Заказы DBS
 *
 * <div class=\"description_important\">     Узнать больше о заказах DBS можно в <a href=\"https://seller.wildberries.ru/instructions/category/6572e024-7428-4db1-86a8-a4c7dbebbfcf?goBackOption=prevRoute&categoryId=5a8e1202-0865-45b7-acae-5d0afc7add56\">справочном центре</a> </div>  Управление [сборочными заданиями](/openapi/orders-dbs#tag/Sborochnye-zadaniya-DBS) и [метаданными](/openapi/orders-dbs#tag/Metadannye-DBS) заказов DBS (Delivery by Seller). 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Meta : Метаданные сборочного задания
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Meta {
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<Box<models::MetaImei>>,
    #[serde(rename = "uin", skip_serializing_if = "Option::is_none")]
    pub uin: Option<Box<models::MetaUin>>,
    #[serde(rename = "gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<Box<models::MetaGtin>>,
    #[serde(rename = "sgtin", skip_serializing_if = "Option::is_none")]
    pub sgtin: Option<Box<models::MetaSgtin>>,
}

impl Meta {
    /// Метаданные сборочного задания
    pub fn new() -> Meta {
        Meta {
            imei: None,
            uin: None,
            gtin: None,
            sgtin: None,
        }
    }
}

