/* tslint:disable */
/* eslint-disable */
/**
 * Работа с товарами
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentV2TagsGet402Response
 */
export interface ContentV2TagsGet402Response {
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof ContentV2TagsGet402Response
     */
    title?: string;
    /**
     * Детали ошибки. Ошибка означает, что на балансе сервиса из [Каталога](https://dev.wildberries.ru/business-solutions) недостаточно средств
     * @type {string}
     * @memberof ContentV2TagsGet402Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the ContentV2TagsGet402Response interface.
 */
export function instanceOfContentV2TagsGet402Response(value: object): value is ContentV2TagsGet402Response {
    return true;
}

export function ContentV2TagsGet402ResponseFromJSON(json: any): ContentV2TagsGet402Response {
    return ContentV2TagsGet402ResponseFromJSONTyped(json, false);
}

export function ContentV2TagsGet402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentV2TagsGet402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ContentV2TagsGet402ResponseToJSON(json: any): ContentV2TagsGet402Response {
    return ContentV2TagsGet402ResponseToJSONTyped(json, false);
}

export function ContentV2TagsGet402ResponseToJSONTyped(value?: ContentV2TagsGet402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
    };
}

