/*
 * Заказы FBS
 *
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    /// Метаданные
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    /// Значение метаданных
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    /// Статус проверки: - IMEI   - `pending` — Маркировка на проверке   - `required` — Обязательная маркировка не заполнена   - `imeiInvalidFormat` — Неверный формат маркировки   - `imeiAlreadySold` — Товар с этим IMEI уже продан - UIN   - `required` — Обязательная маркировка не заполнена   - `pending` — Маркировка на проверке   - `required` — Маркировка обязательна, не заполнена   - `uinInvalidFormat` — Неверный формат маркировки   - `uinNotFound` — Не найден в ГИС   - `uinBadStatus` — Некорректный статус партии   - `uinBadProcess` — Некорректная стадия обработки   - `uinBadStatusAndBadProcess` — Некорректный статус партии. Некорректная стадия обработки - SGTIN   - `required` — Обязательная маркировка не заполнена   - `pending` — Маркировка на проверке   - `sgtinInvalidFormat` — Неверный формат маркировки   - `sgtinNotFound` — Маркировка не найдена в [Честном Знаке](https://chestnyznak.ru)   - `sgtinEmitted` —  Маркировка эмитирована   - `sgtinApplied` — Не пройдена процедура Ввод в оборот   - `sgtinWrittenOff` — Списан   - `sgtinRetired` — Выбыл   - `sgtinWithdrawn` — Выбыл   - `sgtinDisaggregation` — Расформирован   - `sgtinDisaggregated` — Расформирован   - `sgtinAppliedNotPaid` — Не оплачен - GTIN   - `required` — Маркировка обязательна, не заполнена - Expiration   - `required` — Маркировка обязательна, не заполнена - Customs declaration   - `required` — Маркировка обязательна, не заполнена 
    #[serde(rename = "decision", skip_serializing_if = "Option::is_none")]
    pub decision: Option<String>,
}

impl Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    pub fn new() -> Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
        Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
            key: None,
            value: None,
            decision: None,
        }
    }
}

