/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуски](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB <br>    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции по работе с заказами FBS</a>   </div>  <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3PassesPostRequest {
    /// Имя водителя
    #[serde(rename = "firstName")]
    pub first_name: String,
    /// Фамилия водителя
    #[serde(rename = "lastName")]
    pub last_name: String,
    /// Марка машины
    #[serde(rename = "carModel")]
    pub car_model: String,
    /// Номер машины
    #[serde(rename = "carNumber")]
    pub car_number: String,
    /// ID склада
    #[serde(rename = "officeId")]
    pub office_id: i64,
}

impl ApiV3PassesPostRequest {
    pub fn new(first_name: String, last_name: String, car_model: String, car_number: String, office_id: i64) -> ApiV3PassesPostRequest {
        ApiV3PassesPostRequest {
            first_name,
            last_name,
            car_model,
            car_number,
            office_id,
        }
    }
}

