/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуски](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB <br>    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции по работе с заказами FBS</a>   </div>  <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3OrdersStickersPost200ResponseStickersInner {
    /// ID сборочного задания
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    /// Первая часть ID стикера (для печати подписи)
    #[serde(rename = "partA", skip_serializing_if = "Option::is_none")]
    pub part_a: Option<i32>,
    /// Вторая часть ID стикера
    #[serde(rename = "partB", skip_serializing_if = "Option::is_none")]
    pub part_b: Option<i32>,
    /// Закодированное значение стикера
    #[serde(rename = "barcode", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    /// Полное представление стикера в заданном формате (кодировка base64)
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<u8>>,
}

impl ApiV3OrdersStickersPost200ResponseStickersInner {
    pub fn new() -> ApiV3OrdersStickersPost200ResponseStickersInner {
        ApiV3OrdersStickersPost200ResponseStickersInner {
            order_id: None,
            part_a: None,
            part_b: None,
            barcode: None,
            file: None,
        }
    }
}

