/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    /// Стикер в формате PDF, кодировка base64
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<u8>>,
    /// ID сборочного задания
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
    /// Трек-номер в стикере для отслеживания сборочного задания
    #[serde(rename = "parcelId", skip_serializing_if = "Option::is_none")]
    pub parcel_id: Option<String>,
}

impl ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    pub fn new() -> ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
        ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
            file: None,
            order_id: None,
            parcel_id: None,
        }
    }
}

