/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>  С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуски](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB <br>    <div class=\"description_ref\">     Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции по работе с заказами FBS</a>   </div>  <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3OrdersStatusPost200ResponseOrdersInner {
    /// ID сборочного задания
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Статус сборочного задания, установленный продавцом
    #[serde(rename = "supplierStatus", skip_serializing_if = "Option::is_none")]
    pub supplier_status: Option<SupplierStatus>,
    /// Статус сборочного задания в системе Wildberries
    #[serde(rename = "wbStatus", skip_serializing_if = "Option::is_none")]
    pub wb_status: Option<WbStatus>,
}

impl ApiV3OrdersStatusPost200ResponseOrdersInner {
    pub fn new() -> ApiV3OrdersStatusPost200ResponseOrdersInner {
        ApiV3OrdersStatusPost200ResponseOrdersInner {
            id: None,
            supplier_status: None,
            wb_status: None,
        }
    }
}
/// Статус сборочного задания, установленный продавцом
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SupplierStatus {
    #[serde(rename = "new")]
    New,
    #[serde(rename = "confirm")]
    Confirm,
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "cancel")]
    Cancel,
}

impl Default for SupplierStatus {
    fn default() -> SupplierStatus {
        Self::New
    }
}
/// Статус сборочного задания в системе Wildberries
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum WbStatus {
    #[serde(rename = "waiting")]
    Waiting,
    #[serde(rename = "sorted")]
    Sorted,
    #[serde(rename = "sold")]
    Sold,
    #[serde(rename = "canceled")]
    Canceled,
    #[serde(rename = "canceled_by_client")]
    CanceledByClient,
    #[serde(rename = "declined_by_client")]
    DeclinedByClient,
    #[serde(rename = "defect")]
    Defect,
    #[serde(rename = "ready_for_pickup")]
    ReadyForPickup,
    #[serde(rename = "postponed_delivery")]
    PostponedDelivery,
    #[serde(rename = "accepted_by_carrier")]
    AcceptedByCarrier,
    #[serde(rename = "sent_to_carrier")]
    SentToCarrier,
}

impl Default for WbStatus {
    fn default() -> WbStatus {
        Self::Waiting
    }
}

