/*
 * Заказы FBS
 *
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    /// ID сборочного задания
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
    /// Статус генерации стикера:   - `awaitingTrackNumber` — стикер не готов. Ожидается трек-номер от перевозчика.   - `ready` — стикер готов 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<Status>,
    /// Трек-номер в стикере для отслеживания сборочного задания
    #[serde(rename = "parcelId", skip_serializing_if = "Option::is_none")]
    pub parcel_id: Option<String>,
    /// Стикер в формате PDF, кодировка base64
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<u8>>,
}

impl ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    pub fn new() -> ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
        ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
            order_id: None,
            status: None,
            parcel_id: None,
            file: None,
        }
    }
}
/// Статус генерации стикера:   - `awaitingTrackNumber` — стикер не готов. Ожидается трек-номер от перевозчика.   - `ready` — стикер готов 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "awaitingTrackNumber")]
    AwaitingTrackNumber,
    #[serde(rename = "ready")]
    Ready,
}

impl Default for Status {
    fn default() -> Status {
        Self::AwaitingTrackNumber
    }
}

