/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Pass : Данные о пропуске продавца
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Pass {
    /// Имя водителя
    #[serde(rename = "firstName", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<String>,
    /// Дата окончания действия пропуска
    #[serde(rename = "dateEnd", skip_serializing_if = "Option::is_none")]
    pub date_end: Option<String>,
    /// Фамилия водителя
    #[serde(rename = "lastName", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<String>,
    /// Марка машины
    #[serde(rename = "carModel", skip_serializing_if = "Option::is_none")]
    pub car_model: Option<String>,
    /// Номер машины
    #[serde(rename = "carNumber", skip_serializing_if = "Option::is_none")]
    pub car_number: Option<String>,
    /// Название склада
    #[serde(rename = "officeName", skip_serializing_if = "Option::is_none")]
    pub office_name: Option<String>,
    /// Адрес склада
    #[serde(rename = "officeAddress", skip_serializing_if = "Option::is_none")]
    pub office_address: Option<String>,
    /// ID склада
    #[serde(rename = "officeId", skip_serializing_if = "Option::is_none")]
    pub office_id: Option<i64>,
    /// ID пропуска
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
}

impl Pass {
    /// Данные о пропуске продавца
    pub fn new() -> Pass {
        Pass {
            first_name: None,
            date_end: None,
            last_name: None,
            car_model: None,
            car_number: None,
            office_name: None,
            office_address: None,
            office_id: None,
            id: None,
        }
    }
}

