/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplyOrder {
    /// Цена приёмки в копейках. Отображается после фактической приёмки заказа. Для данного метода всегда будет возвращаться `null`. Предоставляется в информационных целях
    #[serde(rename = "scanPrice", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scan_price: Option<Option<f64>>,
    /// ID транзакции для группировки сборочных заданий. Сборочные задания в одной корзине покупателя будут иметь одинаковый `orderUid`
    #[serde(rename = "orderUid", skip_serializing_if = "Option::is_none")]
    pub order_uid: Option<String>,
    /// Артикул продавца
    #[serde(rename = "article", skip_serializing_if = "Option::is_none")]
    pub article: Option<String>,
    /// Код цвета (только для колеруемых товаров)
    #[serde(rename = "colorCode", skip_serializing_if = "Option::is_none")]
    pub color_code: Option<String>,
    /// Уникальный ID заказа. <br> Примечание: `rid` — это `srid` в ответах методов:   - [Заявки покупателей на возврат](./user-communication#tag/Vozvraty-pokupatelyami/paths/~1api~1v1~1claims/get)   - [Заказы](./reports#tag/Osnovnye-otchyoty/paths/~1api~1v1~1supplier~1orders/get)   - [Продажи](./reports#tag/Osnovnye-otchyoty/paths/~1api~1v1~1supplier~1sales/get)   - [Отчет о возвратах и перемещении товаров](./reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov)   - [Отчет о продажах по реализации](./financial-reports-and-accounting#tag/Finansovye-otchyoty/paths/~1api~1v5~1supplier~1reportDetailByPeriod/get) 
    #[serde(rename = "rid", skip_serializing_if = "Option::is_none")]
    pub rid: Option<String>,
    /// Дата создания сборочного задания (RFC3339)
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Список офисов, куда следует привезти товар
    #[serde(rename = "offices", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub offices: Option<Option<Vec<String>>>,
    /// Список баркодов
    #[serde(rename = "skus", skip_serializing_if = "Option::is_none")]
    pub skus: Option<Vec<String>>,
    /// ID сборочного задания
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// ID склада продавца, на который поступило сборочное задание
    #[serde(rename = "warehouseId", skip_serializing_if = "Option::is_none")]
    pub warehouse_id: Option<i32>,
    /// Артикул WB
    #[serde(rename = "nmId", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
    /// ID размера товара в системе WB
    #[serde(rename = "chrtId", skip_serializing_if = "Option::is_none")]
    pub chrt_id: Option<i32>,
    /// Цена в валюте продажи с учётом всех скидок, кроме скидки по WB Кошельку, умноженная на 100. Код валюты продажи — в поле `currencyCode`. Предоставляется в информационных целях 
    #[serde(rename = "price", skip_serializing_if = "Option::is_none")]
    pub price: Option<i32>,
    /// Цена в валюте страны продавца с учетом всех скидок, кроме скидки по WB Кошельку, умноженная на 100. Предоставляется в информационных целях
    #[serde(rename = "convertedPrice", skip_serializing_if = "Option::is_none")]
    pub converted_price: Option<i32>,
    /// Код валюты продажи
    #[serde(rename = "currencyCode", skip_serializing_if = "Option::is_none")]
    pub currency_code: Option<i32>,
    /// Код валюты страны продавца
    #[serde(rename = "convertedCurrencyCode", skip_serializing_if = "Option::is_none")]
    pub converted_currency_code: Option<i32>,
    /// Тип товара:   - `1` — малогабаритный товар (МГТ)   - `2` — сверхгабаритный товар (СГТ)   - `3` — крупногабаритный товар (КГТ+) 
    #[serde(rename = "cargoType", skip_serializing_if = "Option::is_none")]
    pub cargo_type: Option<CargoType>,
    /// Признак заказа товара с нулевым остатком:   - `false` — заказ сделан на товар с ненулевым остатком   - `true` — заказ сделан на товар с нулевым остатком. Такой заказ можно отменить без штрафа за отмену 
    #[serde(rename = "isZeroOrder", skip_serializing_if = "Option::is_none")]
    pub is_zero_order: Option<bool>,
}

impl SupplyOrder {
    pub fn new() -> SupplyOrder {
        SupplyOrder {
            scan_price: None,
            order_uid: None,
            article: None,
            color_code: None,
            rid: None,
            created_at: None,
            offices: None,
            skus: None,
            id: None,
            warehouse_id: None,
            nm_id: None,
            chrt_id: None,
            price: None,
            converted_price: None,
            currency_code: None,
            converted_currency_code: None,
            cargo_type: None,
            is_zero_order: None,
        }
    }
}
/// Тип товара:   - `1` — малогабаритный товар (МГТ)   - `2` — сверхгабаритный товар (СГТ)   - `3` — крупногабаритный товар (КГТ+) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CargoType {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for CargoType {
    fn default() -> CargoType {
        Self::Variant1
    }
}

