/*
 * Заказы FBS
 *
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// V3GetMetaMultiRequest : ID сборочных заданий
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct V3GetMetaMultiRequest {
    #[serde(rename = "orders")]
    pub orders: Vec<i32>,
}

impl V3GetMetaMultiRequest {
    /// ID сборочных заданий
    pub fn new(orders: Vec<i32>) -> V3GetMetaMultiRequest {
        V3GetMetaMultiRequest {
            orders,
        }
    }
}

