/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2GetCardsListPost200ResponseCardsInner {
    /// Артикул WB
    #[serde(rename = "nmID", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
    /// ID объединённой карточки товара.<br>Един для всех артикулов WB одной объединённой карточки товара.<br>Есть у карточки товара, даже если она не объединена ни с одной другой карточкой
    #[serde(rename = "imtID", skip_serializing_if = "Option::is_none")]
    pub imt_id: Option<i32>,
    /// Внутренний технический ID карточки товара
    #[serde(rename = "nmUUID", skip_serializing_if = "Option::is_none")]
    pub nm_uuid: Option<uuid::Uuid>,
    /// ID предмета
    #[serde(rename = "subjectID", skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<i32>,
    /// Название предмета
    #[serde(rename = "subjectName", skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
    /// Артикул продавца
    #[serde(rename = "vendorCode", skip_serializing_if = "Option::is_none")]
    pub vendor_code: Option<String>,
    /// Бренд
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    /// Наименование товара
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Описание товара
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Требуется ли [код маркировки](https://честныйзнак.рф/) для этого товара <br> * `false` — не требуется <br> * `true` — требуется 
    #[serde(rename = "needKiz", skip_serializing_if = "Option::is_none")]
    pub need_kiz: Option<bool>,
    /// Массив фото
    #[serde(rename = "photos", skip_serializing_if = "Option::is_none")]
    pub photos: Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner>>,
    /// URL видео
    #[serde(rename = "video", skip_serializing_if = "Option::is_none")]
    pub video: Option<String>,
    #[serde(rename = "wholesale", skip_serializing_if = "Option::is_none")]
    pub wholesale: Option<Box<models::ContentV2GetCardsListPost200ResponseCardsInnerWholesale>>,
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<Box<models::ContentV2GetCardsListPost200ResponseCardsInnerDimensions>>,
    /// Характеристики
    #[serde(rename = "characteristics", skip_serializing_if = "Option::is_none")]
    pub characteristics: Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerCharacteristicsInner>>,
    /// Размеры товара
    #[serde(rename = "sizes", skip_serializing_if = "Option::is_none")]
    pub sizes: Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerSizesInner>>,
    /// Ярлыки
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerTagsInner>>,
    /// Дата и время создания
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Дата и время изменения
    #[serde(rename = "updatedAt", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<String>,
}

impl ContentV2GetCardsListPost200ResponseCardsInner {
    pub fn new() -> ContentV2GetCardsListPost200ResponseCardsInner {
        ContentV2GetCardsListPost200ResponseCardsInner {
            nm_id: None,
            imt_id: None,
            nm_uuid: None,
            subject_id: None,
            subject_name: None,
            vendor_code: None,
            brand: None,
            title: None,
            description: None,
            need_kiz: None,
            photos: None,
            video: None,
            wholesale: None,
            dimensions: None,
            characteristics: None,
            sizes: None,
            tags: None,
            created_at: None,
            updated_at: None,
        }
    }
}

