/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2GetCardsTrashPost200ResponseCardsInner {
    /// Артикул WB
    #[serde(rename = "nmID", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
    /// Артикул продавца
    #[serde(rename = "vendorCode", skip_serializing_if = "Option::is_none")]
    pub vendor_code: Option<String>,
    /// ID предмета
    #[serde(rename = "subjectID", skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<i32>,
    /// Название предмета
    #[serde(rename = "subjectName", skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
    /// Массив фото
    #[serde(rename = "photos", skip_serializing_if = "Option::is_none")]
    pub photos: Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerPhotosInner>>,
    /// URL видео
    #[serde(rename = "video", skip_serializing_if = "Option::is_none")]
    pub video: Option<String>,
    #[serde(rename = "wholesale", skip_serializing_if = "Option::is_none")]
    pub wholesale: Option<Box<models::ContentV2GetCardsListPost200ResponseCardsInnerWholesale>>,
    /// Массив размеров
    #[serde(rename = "sizes", skip_serializing_if = "Option::is_none")]
    pub sizes: Option<Vec<models::ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner>>,
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<Box<models::ContentV2GetCardsListPost200ResponseCardsInnerDimensions>>,
    /// Характеристики
    #[serde(rename = "characteristics", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub characteristics: Option<Option<Vec<models::ContentV2GetCardsListPost200ResponseCardsInnerCharacteristicsInner>>>,
    /// Date and time the card was created
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    /// Дата и время помещения в корзину
    #[serde(rename = "trashedAt", skip_serializing_if = "Option::is_none")]
    pub trashed_at: Option<String>,
}

impl ContentV2GetCardsTrashPost200ResponseCardsInner {
    pub fn new() -> ContentV2GetCardsTrashPost200ResponseCardsInner {
        ContentV2GetCardsTrashPost200ResponseCardsInner {
            nm_id: None,
            vendor_code: None,
            subject_id: None,
            subject_name: None,
            photos: None,
            video: None,
            wholesale: None,
            sizes: None,
            dimensions: None,
            characteristics: None,
            created_at: None,
            trashed_at: None,
        }
    }
}

