/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner {
    /// ID характеристики
    #[serde(rename = "charcID", skip_serializing_if = "Option::is_none")]
    pub charc_id: Option<i32>,
    /// Название предмета
    #[serde(rename = "subjectName", skip_serializing_if = "Option::is_none")]
    pub subject_name: Option<String>,
    /// ID предмета
    #[serde(rename = "subjectID", skip_serializing_if = "Option::is_none")]
    pub subject_id: Option<i32>,
    /// Название характеристики
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// - `true` - характеристику необходимо обязательно указать в карточке товара - `false` - характеристику необязательно указывать 
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    /// Единица измерения
    #[serde(rename = "unitName", skip_serializing_if = "Option::is_none")]
    pub unit_name: Option<String>,
    /// Максимальное количество значений, которое можно присвоить характеристике при [создании](./work-with-products#tag/Sozdanie-kartochek-tovarov) или [редактировании](./work-with-products#tag/Kartochki-tovarov/paths/~1content~1v2~1cards~1update/post) карточек товаров. <br> Используется только для характеристик с `\"charcType\":1`— массив строк. <br> Характеристикам с `\"charcType\":4`— число, можно присвоить только одно значение. <br><br> Если `\"maxCount\":0`, количество значений не ограничено 
    #[serde(rename = "maxCount", skip_serializing_if = "Option::is_none")]
    pub max_count: Option<i32>,
    /// Характеристика популярна у пользователей (true - да, false - нет)
    #[serde(rename = "popular", skip_serializing_if = "Option::is_none")]
    pub popular: Option<bool>,
    /// Тип данных характеристики, который необходимо использовать при [создании](./work-with-products#tag/Sozdanie-kartochek-tovarov) или [редактировании](./work-with-products#tag/Kartochki-tovarov/paths/~1content~1v2~1cards~1update/post) карточек товаров:   -  `1` — массив строк   -  `4` — число   -  `0` — характеристика не используется 
    #[serde(rename = "charcType", skip_serializing_if = "Option::is_none")]
    pub charc_type: Option<i32>,
}

impl ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner {
    pub fn new() -> ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner {
        ContentV2ObjectCharcsSubjectIdGet200ResponseDataInner {
            charc_id: None,
            subject_name: None,
            subject_id: None,
            name: None,
            required: None,
            unit_name: None,
            max_count: None,
            popular: None,
            charc_type: None,
        }
    }
}

