/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner {
    /// ID размера
    #[serde(rename = "chrtID", skip_serializing_if = "Option::is_none")]
    pub chrt_id: Option<i32>,
    /// Размер товара
    #[serde(rename = "techSize", skip_serializing_if = "Option::is_none")]
    pub tech_size: Option<String>,
    /// Российский размер товара
    #[serde(rename = "wbSize", skip_serializing_if = "Option::is_none")]
    pub wb_size: Option<String>,
    /// Массив баркодов
    #[serde(rename = "skus", skip_serializing_if = "Option::is_none")]
    pub skus: Option<Vec<String>>,
}

impl ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner {
    pub fn new() -> ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner {
        ContentV2GetCardsTrashPost200ResponseCardsInnerSizesInner {
            chrt_id: None,
            tech_size: None,
            wb_size: None,
            skus: None,
        }
    }
}

