/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentV2GetCardsTrashPostRequestSettingsCursor : Пагинатор
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2GetCardsTrashPostRequestSettingsCursor {
    /// Сколько карточек товаров выдать в ответе
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    /// Дата и время помещения в корзину
    #[serde(rename = "trashedAt", skip_serializing_if = "Option::is_none")]
    pub trashed_at: Option<String>,
    /// Артикул WB, с которого надо запрашивать следующий список карточек товаров
    #[serde(rename = "nmID", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
}

impl ContentV2GetCardsTrashPostRequestSettingsCursor {
    /// Пагинатор
    pub fn new() -> ContentV2GetCardsTrashPostRequestSettingsCursor {
        ContentV2GetCardsTrashPostRequestSettingsCursor {
            limit: None,
            trashed_at: None,
            nm_id: None,
        }
    }
}

