/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2CardsUpdatePostRequestInner {
    /// Артикул WB
    #[serde(rename = "nmID")]
    pub nm_id: i32,
    /// Артикул продавца
    #[serde(rename = "vendorCode")]
    pub vendor_code: String,
    /// Бренд
    #[serde(rename = "brand", skip_serializing_if = "Option::is_none")]
    pub brand: Option<String>,
    /// Наименование товара
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Описание товара<br> Максимальное количество символов зависит от категории товара<br> Стандарт — 2000, минимум — 1000, максимум — 5000<br> Подробно о правилах описания в **Правилах заполнения карточки товара** в [Справочном центре](https://seller.wildberries.ru/help-center/article/A-113) на портале продавцов 
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "dimensions", skip_serializing_if = "Option::is_none")]
    pub dimensions: Option<Box<models::ContentV2CardsUpdatePostRequestInnerDimensions>>,
    /// Характеристики товара. <br> Можно получить методом [Характеристики предмета](./work-with-products#tag/Kategorii-predmety-i-harakteristiki/paths/~1content~1v2~1object~1charcs~1%7BsubjectId%7D/get) 
    #[serde(rename = "characteristics", skip_serializing_if = "Option::is_none")]
    pub characteristics: Option<Vec<models::ContentV2CardsUpdatePostRequestInnerCharacteristicsInner>>,
    /// Массив размеров<br> Для безразмерного товара всё равно нужно передавать данный массив без параметров (wbSize и techSize), но с баркодом 
    #[serde(rename = "sizes")]
    pub sizes: Vec<models::ContentV2CardsUpdatePostRequestInnerSizesInner>,
}

impl ContentV2CardsUpdatePostRequestInner {
    pub fn new(nm_id: i32, vendor_code: String, sizes: Vec<models::ContentV2CardsUpdatePostRequestInnerSizesInner>) -> ContentV2CardsUpdatePostRequestInner {
        ContentV2CardsUpdatePostRequestInner {
            nm_id,
            vendor_code,
            brand: None,
            title: None,
            description: None,
            dimensions: None,
            characteristics: None,
            sizes,
        }
    }
}

