/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ContentV2GetCardsListPostRequestSettingsFilter : Параметры фильтрации
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2GetCardsListPostRequestSettingsFilter {
    /// Фильтр по фото:    * `0` — только карточки без фото   * `1` — только карточки с фото   * `-1` — все карточки товара 
    #[serde(rename = "withPhoto", skip_serializing_if = "Option::is_none")]
    pub with_photo: Option<i32>,
    /// Поиск по артикулу продавца, артикулу WB, баркоду
    #[serde(rename = "textSearch", skip_serializing_if = "Option::is_none")]
    pub text_search: Option<String>,
    /// Поиск по ID ярлыков
    #[serde(rename = "tagIDs", skip_serializing_if = "Option::is_none")]
    pub tag_ids: Option<Vec<i32>>,
    /// Фильтр по категории. `true` - только разрешённые, `false` - все. Не используется в песочнице
    #[serde(rename = "allowedCategoriesOnly", skip_serializing_if = "Option::is_none")]
    pub allowed_categories_only: Option<bool>,
    /// Поиск по id предметов
    #[serde(rename = "objectIDs", skip_serializing_if = "Option::is_none")]
    pub object_ids: Option<Vec<i32>>,
    /// Поиск по брендам
    #[serde(rename = "brands", skip_serializing_if = "Option::is_none")]
    pub brands: Option<Vec<String>>,
    /// Поиск по ID объединённой карточки товара
    #[serde(rename = "imtID", skip_serializing_if = "Option::is_none")]
    pub imt_id: Option<i32>,
}

impl ContentV2GetCardsListPostRequestSettingsFilter {
    /// Параметры фильтрации
    pub fn new() -> ContentV2GetCardsListPostRequestSettingsFilter {
        ContentV2GetCardsListPostRequestSettingsFilter {
            with_photo: None,
            text_search: None,
            tag_ids: None,
            allowed_categories_only: None,
            object_ids: None,
            brands: None,
            imt_id: None,
        }
    }
}

