/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ContentV2CardsUploadPostRequestInner {
    /// ID предмета
    #[serde(rename = "subjectID")]
    pub subject_id: i32,
    /// Массив вариантов товара.<br> В каждой объединённой карточке товара может быть не более 30 карточек товаров 
    #[serde(rename = "variants")]
    pub variants: Vec<models::ContentV2CardsUploadPostRequestInnerVariantsInner>,
}

impl ContentV2CardsUploadPostRequestInner {
    pub fn new(subject_id: i32, variants: Vec<models::ContentV2CardsUploadPostRequestInnerVariantsInner>) -> ContentV2CardsUploadPostRequestInner {
        ContentV2CardsUploadPostRequestInner {
            subject_id,
            variants,
        }
    }
}

