/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BrandsResponseError {
    /// Заголовок ошибки
    #[serde(rename = "title")]
    pub title: String,
    /// Детали ошибки
    #[serde(rename = "detail")]
    pub detail: String,
    /// ID внутреннего сервиса WB
    #[serde(rename = "origin")]
    pub origin: String,
    /// Уникальный ID запроса
    #[serde(rename = "requestId")]
    pub request_id: String,
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::BrandsResponseErrorErrorsInner>>,
}

impl BrandsResponseError {
    pub fn new(title: String, detail: String, origin: String, request_id: String) -> BrandsResponseError {
        BrandsResponseError {
            title,
            detail,
            origin,
            request_id,
            errors: None,
        }
    }
}

