/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ModelsErrorTableListPublicRespV2 : Данные ответа
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsErrorTableListPublicRespV2 {
    /// Пакеты данных
    #[serde(rename = "items")]
    pub items: Vec<models::ModelsErrorTableListPublicRespV2Item>,
    #[serde(rename = "cursor")]
    pub cursor: Box<models::ViewerContractPublicErrorsCursorOutput>,
}

impl ModelsErrorTableListPublicRespV2 {
    /// Данные ответа
    pub fn new(items: Vec<models::ModelsErrorTableListPublicRespV2Item>, cursor: models::ViewerContractPublicErrorsCursorOutput) -> ModelsErrorTableListPublicRespV2 {
        ModelsErrorTableListPublicRespV2 {
            items,
            cursor: Box::new(cursor),
        }
    }
}

