/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ModelsErrorTableListPublicRespV2Item {
    /// ID пакета
    #[serde(rename = "batchUUID")]
    pub batch_uuid: uuid::Uuid,
    /// Предметы. Разбивка по `vendorCodes`
    #[serde(rename = "subjects")]
    pub subjects: std::collections::HashMap<String, models::ModelsErrorSubject>,
    /// Бренды. Разбивка по `vendorCodes`
    #[serde(rename = "brands")]
    pub brands: std::collections::HashMap<String, models::ModelsErrorBrand>,
    /// Артикулы продавца
    #[serde(rename = "vendorCodes")]
    pub vendor_codes: Vec<String>,
    /// Ошибки. Разбивка по `vendorCodes`
    #[serde(rename = "errors")]
    pub errors: std::collections::HashMap<String, Vec<String>>,
}

impl ModelsErrorTableListPublicRespV2Item {
    pub fn new(batch_uuid: uuid::Uuid, subjects: std::collections::HashMap<String, models::ModelsErrorSubject>, brands: std::collections::HashMap<String, models::ModelsErrorBrand>, vendor_codes: Vec<String>, errors: std::collections::HashMap<String, Vec<String>>) -> ModelsErrorTableListPublicRespV2Item {
        ModelsErrorTableListPublicRespV2Item {
            batch_uuid,
            subjects,
            brands,
            vendor_codes,
            errors,
        }
    }
}

