/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplierTaskMetadataBuffer : Данные ответа
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierTaskMetadataBuffer {
    /// ID загрузки
    #[serde(rename = "uploadID", skip_serializing_if = "Option::is_none")]
    pub upload_id: Option<i32>,
    /// Статус загрузки: `1` — в обработке 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    /// Дата и время, когда загрузка создана
    #[serde(rename = "uploadDate", skip_serializing_if = "Option::is_none")]
    pub upload_date: Option<String>,
    /// Дата и время, когда загрузка отправляется в обработку
    #[serde(rename = "activationDate", skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<String>,
    /// Всего товаров
    #[serde(rename = "overAllGoodsNumber", skip_serializing_if = "Option::is_none")]
    pub over_all_goods_number: Option<i32>,
    /// Товаров без ошибок (0, потому что загрузка в обработке)
    #[serde(rename = "successGoodsNumber", skip_serializing_if = "Option::is_none")]
    pub success_goods_number: Option<i32>,
}

impl SupplierTaskMetadataBuffer {
    /// Данные ответа
    pub fn new() -> SupplierTaskMetadataBuffer {
        SupplierTaskMetadataBuffer {
            upload_id: None,
            status: None,
            upload_date: None,
            activation_date: None,
            over_all_goods_number: None,
            success_goods_number: None,
        }
    }
}

