/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplierTaskMetadata : Данные ответа
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierTaskMetadata {
    /// ID загрузки
    #[serde(rename = "uploadID", skip_serializing_if = "Option::is_none")]
    pub upload_id: Option<i32>,
    /// Статус загрузки:   * `3` — обработана, в товарах нет ошибок, цены и скидки обновились   * `4` — отменена   * `5` — обработана, но в товарах есть ошибки. Для товаров без ошибок цены и скидки обновились, а ошибки в остальных товарах можно получить с помощью метода [Детализация обработанной загрузки](./work-with-products#tag/Ceny-i-skidki/paths/~1api~1v2~1history~1goods~1task/get)   * `6` — обработана, но во всех товарах есть ошибки. Их тоже можно получить с помощью метода [Детализация обработанной загрузки](./work-with-products#tag/Ceny-i-skidki/paths/~1api~1v2~1history~1goods~1task/get) 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    /// Дата и время, когда загрузка создана
    #[serde(rename = "uploadDate", skip_serializing_if = "Option::is_none")]
    pub upload_date: Option<String>,
    /// Дата и время, когда загрузка отправляется в обработку
    #[serde(rename = "activationDate", skip_serializing_if = "Option::is_none")]
    pub activation_date: Option<String>,
    /// Всего товаров
    #[serde(rename = "overAllGoodsNumber", skip_serializing_if = "Option::is_none")]
    pub over_all_goods_number: Option<i32>,
    /// Товаров без ошибок
    #[serde(rename = "successGoodsNumber", skip_serializing_if = "Option::is_none")]
    pub success_goods_number: Option<i32>,
}

impl SupplierTaskMetadata {
    /// Данные ответа
    pub fn new() -> SupplierTaskMetadata {
        SupplierTaskMetadata {
            upload_id: None,
            status: None,
            upload_date: None,
            activation_date: None,
            over_all_goods_number: None,
            success_goods_number: None,
        }
    }
}

