/*
 * Работа с товарами
 *
 * С помощью методов этого раздела вы можете:   - [создать](/openapi/work-with-products#tag/Sozdanie-kartochek-tovarov) и [редактировать](/openapi/work-with-products#tag/Kartochki-tovarov) карточки товаров   - получить [категории, предметы, характеристики и бренды товаров](/openapi/work-with-products#tag/Kategorii-predmety-i-harakteristiki)   - загрузить [медиафайлы](/openapi/work-with-products#tag/Mediafajly) в карточки товаров   - настроить [ярлыки](/openapi/work-with-products#tag/Yarlyki) для поиска товаров   - установить [цены и скидки](/openapi/work-with-products#tag/Ceny-i-skidki)   - управлять [остатками товаров](/openapi/work-with-products#tag/Ostatki-na-skladah-prodavca) и [складами](/openapi/work-with-products#tag/Sklady-prodavca), если вы работаете по модели продаж со склада продавца    <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/101\">инструкции по работе с товарами</a>   </div> 
 *
 * The version of the OpenAPI document: products
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Warehouse : Данные о складе продавца
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Warehouse {
    /// Название склада продавца
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID склада WB
    #[serde(rename = "officeId", skip_serializing_if = "Option::is_none")]
    pub office_id: Option<i64>,
    /// ID склада продавца
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Тип товара:   - `1` — малогабаритный товар (МГТ)   - `2` — сверхгабаритный товар (СГТ)   - `3` — крупногабаритный товар (КГТ+) 
    #[serde(rename = "cargoType", skip_serializing_if = "Option::is_none")]
    pub cargo_type: Option<CargoType>,
    /// Тип доставки, который принимает склад:   - `1` — доставка на склад WB (FBS)   - `2` — доставка силами продавца (DBS)   - `3` — доставка курьером WB (DBW)   - `5` — самовывоз (C&C)   - `6` — экспресс-доставка силами продавца (ЕDBS) 
    #[serde(rename = "deliveryType", skip_serializing_if = "Option::is_none")]
    pub delivery_type: Option<DeliveryType>,
    /// Склад удаляется:   - `false` — нет   - `true` — да  После удаления склад пропадёт из списка 
    #[serde(rename = "isDeleting", skip_serializing_if = "Option::is_none")]
    pub is_deleting: Option<bool>,
    /// Данные склада обновляются:   - `false` — нет   - `true` — да, обновление и удаление остатков недоступно  Обновление данных может занимать несколько минут 
    #[serde(rename = "isProcessing", skip_serializing_if = "Option::is_none")]
    pub is_processing: Option<bool>,
}

impl Warehouse {
    /// Данные о складе продавца
    pub fn new() -> Warehouse {
        Warehouse {
            name: None,
            office_id: None,
            id: None,
            cargo_type: None,
            delivery_type: None,
            is_deleting: None,
            is_processing: None,
        }
    }
}
/// Тип товара:   - `1` — малогабаритный товар (МГТ)   - `2` — сверхгабаритный товар (СГТ)   - `3` — крупногабаритный товар (КГТ+) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CargoType {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
}

impl Default for CargoType {
    fn default() -> CargoType {
        Self::Variant1
    }
}
/// Тип доставки, который принимает склад:   - `1` — доставка на склад WB (FBS)   - `2` — доставка силами продавца (DBS)   - `3` — доставка курьером WB (DBW)   - `5` — самовывоз (C&C)   - `6` — экспресс-доставка силами продавца (ЕDBS) 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeliveryType {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "2")]
    Variant2,
    #[serde(rename = "3")]
    Variant3,
    #[serde(rename = "5")]
    Variant5,
    #[serde(rename = "6")]
    Variant6,
}

impl Default for DeliveryType {
    fn default() -> DeliveryType {
        Self::Variant1
    }
}

