/*
Аналитика и данные

<div class=\"description_important\">   Узнать больше об аналитике и данных можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/subcategory/seller-analytics\">справочном центре</a> </div>  <div class=\"api-block\">  В разделе описаны методы получения:   1. [Воронки продаж](/openapi/analytics#tag/Voronka-prodazh)   2. [Поисковых запросов по вашим товарам](/openapi/analytics#tag/Poiskovye-zaprosy-po-vashim-tovaram)   3. [Истории остатков](/openapi/analytics#tag/Istoriya-ostatkov)   4. [Оценки товара](/openapi/analytics#tag/Ocenka-tovara)   5. [Аналитики продавца в формате CSV](/openapi/analytics#tag/Analitika-prodavca-CSV)  </div> 

API version: analytics
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package analytics

import (
	"encoding/json"
)

// checks if the DistributionTableIndicators type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DistributionTableIndicators{}

// DistributionTableIndicators struct for DistributionTableIndicators
type DistributionTableIndicators struct {
	FeedbackCount *CommonInfoAdvertisedProducts `json:"feedbackCount,omitempty"`
	FiveStar *CommonInfoAdvertisedProducts `json:"fiveStar,omitempty"`
	FourStar *CommonInfoAdvertisedProducts `json:"fourStar,omitempty"`
	ThreeStar *CommonInfoAdvertisedProducts `json:"threeStar,omitempty"`
	TwoStar *CommonInfoAdvertisedProducts `json:"twoStar,omitempty"`
	OneStar *CommonInfoAdvertisedProducts `json:"oneStar,omitempty"`
	// Отзывы, исключённые из рейтинга
	Disqualified *int32 `json:"disqualified,omitempty"`
}

// NewDistributionTableIndicators instantiates a new DistributionTableIndicators object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDistributionTableIndicators() *DistributionTableIndicators {
	this := DistributionTableIndicators{}
	return &this
}

// NewDistributionTableIndicatorsWithDefaults instantiates a new DistributionTableIndicators object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDistributionTableIndicatorsWithDefaults() *DistributionTableIndicators {
	this := DistributionTableIndicators{}
	return &this
}

// GetFeedbackCount returns the FeedbackCount field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetFeedbackCount() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.FeedbackCount) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.FeedbackCount
}

// GetFeedbackCountOk returns a tuple with the FeedbackCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetFeedbackCountOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.FeedbackCount) {
		return nil, false
	}
	return o.FeedbackCount, true
}

// HasFeedbackCount returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasFeedbackCount() bool {
	if o != nil && !IsNil(o.FeedbackCount) {
		return true
	}

	return false
}

// SetFeedbackCount gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the FeedbackCount field.
func (o *DistributionTableIndicators) SetFeedbackCount(v CommonInfoAdvertisedProducts) {
	o.FeedbackCount = &v
}

// GetFiveStar returns the FiveStar field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetFiveStar() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.FiveStar) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.FiveStar
}

// GetFiveStarOk returns a tuple with the FiveStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetFiveStarOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.FiveStar) {
		return nil, false
	}
	return o.FiveStar, true
}

// HasFiveStar returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasFiveStar() bool {
	if o != nil && !IsNil(o.FiveStar) {
		return true
	}

	return false
}

// SetFiveStar gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the FiveStar field.
func (o *DistributionTableIndicators) SetFiveStar(v CommonInfoAdvertisedProducts) {
	o.FiveStar = &v
}

// GetFourStar returns the FourStar field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetFourStar() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.FourStar) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.FourStar
}

// GetFourStarOk returns a tuple with the FourStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetFourStarOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.FourStar) {
		return nil, false
	}
	return o.FourStar, true
}

// HasFourStar returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasFourStar() bool {
	if o != nil && !IsNil(o.FourStar) {
		return true
	}

	return false
}

// SetFourStar gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the FourStar field.
func (o *DistributionTableIndicators) SetFourStar(v CommonInfoAdvertisedProducts) {
	o.FourStar = &v
}

// GetThreeStar returns the ThreeStar field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetThreeStar() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.ThreeStar) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.ThreeStar
}

// GetThreeStarOk returns a tuple with the ThreeStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetThreeStarOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.ThreeStar) {
		return nil, false
	}
	return o.ThreeStar, true
}

// HasThreeStar returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasThreeStar() bool {
	if o != nil && !IsNil(o.ThreeStar) {
		return true
	}

	return false
}

// SetThreeStar gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the ThreeStar field.
func (o *DistributionTableIndicators) SetThreeStar(v CommonInfoAdvertisedProducts) {
	o.ThreeStar = &v
}

// GetTwoStar returns the TwoStar field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetTwoStar() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.TwoStar) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.TwoStar
}

// GetTwoStarOk returns a tuple with the TwoStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetTwoStarOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.TwoStar) {
		return nil, false
	}
	return o.TwoStar, true
}

// HasTwoStar returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasTwoStar() bool {
	if o != nil && !IsNil(o.TwoStar) {
		return true
	}

	return false
}

// SetTwoStar gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the TwoStar field.
func (o *DistributionTableIndicators) SetTwoStar(v CommonInfoAdvertisedProducts) {
	o.TwoStar = &v
}

// GetOneStar returns the OneStar field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetOneStar() CommonInfoAdvertisedProducts {
	if o == nil || IsNil(o.OneStar) {
		var ret CommonInfoAdvertisedProducts
		return ret
	}
	return *o.OneStar
}

// GetOneStarOk returns a tuple with the OneStar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetOneStarOk() (*CommonInfoAdvertisedProducts, bool) {
	if o == nil || IsNil(o.OneStar) {
		return nil, false
	}
	return o.OneStar, true
}

// HasOneStar returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasOneStar() bool {
	if o != nil && !IsNil(o.OneStar) {
		return true
	}

	return false
}

// SetOneStar gets a reference to the given CommonInfoAdvertisedProducts and assigns it to the OneStar field.
func (o *DistributionTableIndicators) SetOneStar(v CommonInfoAdvertisedProducts) {
	o.OneStar = &v
}

// GetDisqualified returns the Disqualified field value if set, zero value otherwise.
func (o *DistributionTableIndicators) GetDisqualified() int32 {
	if o == nil || IsNil(o.Disqualified) {
		var ret int32
		return ret
	}
	return *o.Disqualified
}

// GetDisqualifiedOk returns a tuple with the Disqualified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DistributionTableIndicators) GetDisqualifiedOk() (*int32, bool) {
	if o == nil || IsNil(o.Disqualified) {
		return nil, false
	}
	return o.Disqualified, true
}

// HasDisqualified returns a boolean if a field has been set.
func (o *DistributionTableIndicators) HasDisqualified() bool {
	if o != nil && !IsNil(o.Disqualified) {
		return true
	}

	return false
}

// SetDisqualified gets a reference to the given int32 and assigns it to the Disqualified field.
func (o *DistributionTableIndicators) SetDisqualified(v int32) {
	o.Disqualified = &v
}

func (o DistributionTableIndicators) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DistributionTableIndicators) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FeedbackCount) {
		toSerialize["feedbackCount"] = o.FeedbackCount
	}
	if !IsNil(o.FiveStar) {
		toSerialize["fiveStar"] = o.FiveStar
	}
	if !IsNil(o.FourStar) {
		toSerialize["fourStar"] = o.FourStar
	}
	if !IsNil(o.ThreeStar) {
		toSerialize["threeStar"] = o.ThreeStar
	}
	if !IsNil(o.TwoStar) {
		toSerialize["twoStar"] = o.TwoStar
	}
	if !IsNil(o.OneStar) {
		toSerialize["oneStar"] = o.OneStar
	}
	if !IsNil(o.Disqualified) {
		toSerialize["disqualified"] = o.Disqualified
	}
	return toSerialize, nil
}

type NullableDistributionTableIndicators struct {
	value *DistributionTableIndicators
	isSet bool
}

func (v NullableDistributionTableIndicators) Get() *DistributionTableIndicators {
	return v.value
}

func (v *NullableDistributionTableIndicators) Set(val *DistributionTableIndicators) {
	v.value = val
	v.isSet = true
}

func (v NullableDistributionTableIndicators) IsSet() bool {
	return v.isSet
}

func (v *NullableDistributionTableIndicators) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDistributionTableIndicators(val *DistributionTableIndicators) *NullableDistributionTableIndicators {
	return &NullableDistributionTableIndicators{value: val, isSet: true}
}

func (v NullableDistributionTableIndicators) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDistributionTableIndicators) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


