/*
 * Отчёты
 *
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  С помощью этих методов вы можете получить [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Платной приёмке](/openapi/reports#tag/Platnaya-priyomka)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Скрытых товарах](/openapi/reports#tag/Skrytye-tovary)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov) 
 *
 * The version of the OpenAPI document: reports
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
    /// Сумма штрафа в копейках
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount: Option<i32>,
    /// Дата изменения характеристик товара на складе
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Новый баркод в карточке товара
    #[serde(rename = "newBarcode", skip_serializing_if = "Option::is_none")]
    pub new_barcode: Option<String>,
    /// Новый цвет
    #[serde(rename = "newColor", skip_serializing_if = "Option::is_none")]
    pub new_color: Option<String>,
    /// Новый артикул продавца
    #[serde(rename = "newSa", skip_serializing_if = "Option::is_none")]
    pub new_sa: Option<String>,
    /// Новый штрихкод товара в WB
    #[serde(rename = "newShkID", skip_serializing_if = "Option::is_none")]
    pub new_shk_id: Option<i32>,
    /// Новый размер
    #[serde(rename = "newSize", skip_serializing_if = "Option::is_none")]
    pub new_size: Option<String>,
    /// Артикул WB
    #[serde(rename = "nmID", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
    /// Старый баркод из карточки товара
    #[serde(rename = "oldBarcode", skip_serializing_if = "Option::is_none")]
    pub old_barcode: Option<String>,
    /// Старый цвет
    #[serde(rename = "oldColor", skip_serializing_if = "Option::is_none")]
    pub old_color: Option<String>,
    /// Старый артикул продавца
    #[serde(rename = "oldSa", skip_serializing_if = "Option::is_none")]
    pub old_sa: Option<String>,
    /// Старый штрихкод товара в WB
    #[serde(rename = "oldShkID", skip_serializing_if = "Option::is_none")]
    pub old_shk_id: Option<i32>,
    /// Старый размер
    #[serde(rename = "oldSize", skip_serializing_if = "Option::is_none")]
    pub old_size: Option<String>,
}

impl ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
    pub fn new() -> ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
        ApiV1AnalyticsCharacteristicsChangeGet200ResponseReportInner {
            amount: None,
            date: None,
            new_barcode: None,
            new_color: None,
            new_sa: None,
            new_shk_id: None,
            new_size: None,
            nm_id: None,
            old_barcode: None,
            old_color: None,
            old_sa: None,
            old_shk_id: None,
            old_size: None,
        }
    }
}

