/*
 * Отчёты
 *
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  С помощью этих методов вы можете получить [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Платной приёмке](/openapi/reports#tag/Platnaya-priyomka)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Скрытых товарах](/openapi/reports#tag/Skrytye-tovary)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov) 
 *
 * The version of the OpenAPI document: reports
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MeasurementDataReportsInner {
    /// Артикул WB
    #[serde(rename = "nmId", skip_serializing_if = "Option::is_none")]
    pub nm_id: Option<i32>,
    /// Предмет
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<String>,
    /// ID замера
    #[serde(rename = "dimId", skip_serializing_if = "Option::is_none")]
    pub dim_id: Option<i32>,
    /// Разница в габаритах, %
    #[serde(rename = "prcOver", skip_serializing_if = "Option::is_none")]
    pub prc_over: Option<f64>,
    /// Объём, л (фактические габариты)
    #[serde(rename = "volume", skip_serializing_if = "Option::is_none")]
    pub volume: Option<f64>,
    /// Ширина, см (фактические габариты)
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,
    /// Длина, см (фактические габариты)
    #[serde(rename = "length", skip_serializing_if = "Option::is_none")]
    pub length: Option<i32>,
    /// Высота, см (фактические габариты)
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,
    /// Объём, л (габариты карточки товара)
    #[serde(rename = "volumeSup", skip_serializing_if = "Option::is_none")]
    pub volume_sup: Option<f64>,
    /// Ширина, см (габариты карточки товара)
    #[serde(rename = "widthSup", skip_serializing_if = "Option::is_none")]
    pub width_sup: Option<i32>,
    /// Длина, см (габариты карточки товара)
    #[serde(rename = "lengthSup", skip_serializing_if = "Option::is_none")]
    pub length_sup: Option<i32>,
    /// Высота, см (габариты карточки товара)
    #[serde(rename = "heightSup", skip_serializing_if = "Option::is_none")]
    pub height_sup: Option<i32>,
    /// Фото замеров
    #[serde(rename = "photoUrls", skip_serializing_if = "Option::is_none")]
    pub photo_urls: Option<Vec<String>>,
    /// Дата и время
    #[serde(rename = "dt", skip_serializing_if = "Option::is_none")]
    pub dt: Option<String>,
    /// Дата начала замера 
    #[serde(rename = "dateStart", skip_serializing_if = "Option::is_none")]
    pub date_start: Option<String>,
    /// Дата конца замера
    #[serde(rename = "dateEnd", skip_serializing_if = "Option::is_none")]
    pub date_end: Option<String>,
}

impl MeasurementDataReportsInner {
    pub fn new() -> MeasurementDataReportsInner {
        MeasurementDataReportsInner {
            nm_id: None,
            subject: None,
            dim_id: None,
            prc_over: None,
            volume: None,
            width: None,
            length: None,
            height: None,
            volume_sup: None,
            width_sup: None,
            length_sup: None,
            height_sup: None,
            photo_urls: None,
            dt: None,
            date_start: None,
            date_end: None,
        }
    }
}

