/*
 * Отчёты
 *
 * <div class=\"description_important\">   Узнать больше об отчётах можно в <a href=\"https://seller.wildberries.ru/instructions/subcategory/5f2162c5-069b-416d-a4e1-48da2a76e6b0\">справочном центре</a> </div>  С помощью этих методов вы можете получить [основные отчёты](/openapi/reports#tag/Osnovnye-otchyoty) и отчёты о:   1. [Остатках на складах](/openapi/reports#tag/Otchyot-ob-ostatkah-na-skladah)   2. [Товарах с обязательной маркировкой](/openapi/reports#tag/Otchyot-o-tovarah-c-obyazatelnoj-markirovkoj)   3. [Удержаниях](/openapi/reports#tag/Otchyoty-ob-uderzhaniyah)   4. [Платной приёмке](/openapi/reports#tag/Platnaya-priyomka)   5. [Платном хранении](/openapi/reports#tag/Platnoe-hranenie)   6. [Продажах по регионам](/openapi/reports#tag/Prodazhi-po-regionam)   7. [Доле бренда в продажах](/openapi/reports#tag/Dolya-brenda-v-prodazhah)   8. [Скрытых товарах](/openapi/reports#tag/Skrytye-tovary)   9. [Возвратах и перемещении товаров](/openapi/reports#tag/Otchyot-o-vozvratah-i-peremeshenii-tovarov) 
 *
 * The version of the OpenAPI document: reports
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PenaltyData : Данные ответа
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PenaltyData {
    /// Удержания
    #[serde(rename = "reports")]
    pub reports: Vec<models::PenaltyDataReportsInner>,
    /// Количество удержаний в отчёте. Без учёта `limit` и `offset`
    #[serde(rename = "totalCount")]
    pub total_count: i32,
}

impl PenaltyData {
    /// Данные ответа
    pub fn new(reports: Vec<models::PenaltyDataReportsInner>, total_count: i32) -> PenaltyData {
        PenaltyData {
            reports,
            total_count,
        }
    }
}

