/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
    /// IMEI
    #[serde(rename = "imei")]
    pub imei: String,
}

impl ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
    pub fn new(imei: String) -> ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
        ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
            imei,
        }
    }
}

