/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersNewGet401Response {
    /// Заголовок ошибки
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Детали ошибки
    #[serde(rename = "detail", skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    /// Внутренний код ошибки
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Уникальный ID запроса
    #[serde(rename = "requestId", skip_serializing_if = "Option::is_none")]
    pub request_id: Option<String>,
    /// ID внутреннего сервиса WB
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    /// HTTP статус-код
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<f64>,
    /// Расшифровка HTTP статус-кода
    #[serde(rename = "statusText", skip_serializing_if = "Option::is_none")]
    pub status_text: Option<String>,
    /// Дата и время запроса
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
}

impl ApiV3DbwOrdersNewGet401Response {
    pub fn new() -> ApiV3DbwOrdersNewGet401Response {
        ApiV3DbwOrdersNewGet401Response {
            title: None,
            detail: None,
            code: None,
            request_id: None,
            origin: None,
            status: None,
            status_text: None,
            timestamp: None,
        }
    }
}

