/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции по работе с заказами DBW</a> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersGet200Response {
    /// Параметр пагинации. Содержит значение, которое необходимо указать в запросе для получения следующего пакета данных
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<i64>,
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<Vec<models::Order>>,
}

impl ApiV3DbwOrdersGet200Response {
    pub fn new() -> ApiV3DbwOrdersGet200Response {
        ApiV3DbwOrdersGet200Response {
            next: None,
            orders: None,
        }
    }
}

