/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции по работе с заказами DBW</a> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_with::serde_as;

#[serde_as]
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersStickersPost200ResponseStickersInner {
    /// ID сборочного задания
    #[serde(rename = "orderId", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i64>,
    /// Первая часть ID стикера (для печати подписи)
    #[serde(rename = "partA", skip_serializing_if = "Option::is_none")]
    pub part_a: Option<String>,
    /// Вторая часть ID стикера
    #[serde(rename = "partB", skip_serializing_if = "Option::is_none")]
    pub part_b: Option<String>,
    /// Закодированное значение стикера
    #[serde(rename = "barcode", skip_serializing_if = "Option::is_none")]
    pub barcode: Option<String>,
    /// Полное представление стикера в заданном формате (кодировка base64)
    #[serde_as(as = "Option<serde_with::base64::Base64>")]
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<u8>>,
}

impl ApiV3DbwOrdersStickersPost200ResponseStickersInner {
    pub fn new() -> ApiV3DbwOrdersStickersPost200ResponseStickersInner {
        ApiV3DbwOrdersStickersPost200ResponseStickersInner {
            order_id: None,
            part_a: None,
            part_b: None,
            barcode: None,
            file: None,
        }
    }
}

