/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersStatusPost200ResponseOrdersInner {
    /// ID сборочного задания
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    /// Статус сборочного задания, установленный продавцом
    #[serde(rename = "supplierStatus", skip_serializing_if = "Option::is_none")]
    pub supplier_status: Option<String>,
    /// Статус сборочного задания в системе Wildberries
    #[serde(rename = "wbStatus", skip_serializing_if = "Option::is_none")]
    pub wb_status: Option<String>,
}

impl ApiV3DbwOrdersStatusPost200ResponseOrdersInner {
    pub fn new() -> ApiV3DbwOrdersStatusPost200ResponseOrdersInner {
        ApiV3DbwOrdersStatusPost200ResponseOrdersInner {
            id: None,
            supplier_status: None,
            wb_status: None,
        }
    }
}

