/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersStatusPostRequest {
    /// Список ID сборочных заданий
    #[serde(rename = "orders")]
    pub orders: Vec<i64>,
}

impl ApiV3DbwOrdersStatusPostRequest {
    pub fn new(orders: Vec<i64>) -> ApiV3DbwOrdersStatusPostRequest {
        ApiV3DbwOrdersStatusPostRequest {
            orders,
        }
    }
}

