/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
    /// IMEI
    #[serde(rename = "imei")]
    pub imei: String,
}

impl ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
    pub fn new(imei: String) -> ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
        ApiV3DbwOrdersOrderIdMetaImeiPutRequest {
            imei,
        }
    }
}

