/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CourierContactsResponse {
    /// Номер автомобиля
    #[serde(rename = "carNumber", skip_serializing_if = "Option::is_none")]
    pub car_number: Option<String>,
    /// ФИО курьера
    #[serde(rename = "fullName", skip_serializing_if = "Option::is_none")]
    pub full_name: Option<String>,
    /// Номер телефона
    #[serde(rename = "phone", skip_serializing_if = "Option::is_none")]
    pub phone: Option<String>,
}

impl CourierContactsResponse {
    pub fn new() -> CourierContactsResponse {
        CourierContactsResponse {
            car_number: None,
            full_name: None,
            phone: None,
        }
    }
}

