/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// MetaSgtin : Код маркировки Честного знака
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetaSgtin {
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<Vec<String>>>,
}

impl MetaSgtin {
    /// Код маркировки Честного знака
    pub fn new() -> MetaSgtin {
        MetaSgtin {
            value: None,
        }
    }
}

