/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderCourierInfo {
    /// Информация о курьере
    #[serde(rename = "courierInfo", skip_serializing_if = "Option::is_none")]
    pub courier_info: Option<Box<models::CourierInfo>>,
    /// ID сборочного задания
    #[serde(rename = "orderID", skip_serializing_if = "Option::is_none")]
    pub order_id: Option<i32>,
}

impl OrderCourierInfo {
    pub fn new() -> OrderCourierInfo {
        OrderCourierInfo {
            courier_info: None,
            order_id: None,
        }
    }
}

