/*
 * Заказы DBW
 *
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции по работе с заказами DBW</a> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderNewDbwAddress : Адрес покупателя для доставки
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderNewDbwAddress {
    /// Адрес доставки
    #[serde(rename = "fullAddress", skip_serializing_if = "Option::is_none")]
    pub full_address: Option<String>,
    /// Долгота
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// Широта
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
}

impl OrderNewDbwAddress {
    /// Адрес покупателя для доставки
    pub fn new() -> OrderNewDbwAddress {
        OrderNewDbwAddress {
            full_address: None,
            longitude: None,
            latitude: None,
        }
    }
}

