/*
 * Заказы DBW
 *
 * Управление [сборочными заданиями](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW) и [метаданными](/openapi/orders-dbw#tag/Metadannye-DBW) заказов DBW (Доставка курьером WB).
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OrderNewDbwAddress : Адрес покупателя для доставки
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OrderNewDbwAddress {
    /// Адрес доставки
    #[serde(rename = "fullAddress", skip_serializing_if = "Option::is_none")]
    pub full_address: Option<String>,
    /// Долгота
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// Широта
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
}

impl OrderNewDbwAddress {
    /// Адрес покупателя для доставки
    pub fn new() -> OrderNewDbwAddress {
        OrderNewDbwAddress {
            full_address: None,
            longitude: None,
            latitude: None,
        }
    }
}

