/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner
 */
export interface ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    /**
     * Стикер в формате PDF, кодировка base64
     * @type {string}
     * @memberof ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner
     */
    file?: string;
    /**
     * ID сборочного задания
     * @type {number}
     * @memberof ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner
     */
    orderId?: number;
    /**
     * Трек-номер в стикере для отслеживания сборочного задания
     * @type {string}
     * @memberof ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner
     */
    parcelId?: string;
}

/**
 * Check if a given object implements the ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner interface.
 */
export function instanceOfApiV3OrdersStickersCrossBorderPost200ResponseStickersInner(value: object): value is ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return true;
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSON(json: any): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSONTyped(json, false);
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'file': json['file'] == null ? undefined : json['file'],
        'orderId': json['orderId'] == null ? undefined : json['orderId'],
        'parcelId': json['parcelId'] == null ? undefined : json['parcelId'],
    };
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSON(json: any): ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner {
    return ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSONTyped(json, false);
}

export function ApiV3OrdersStickersCrossBorderPost200ResponseStickersInnerToJSONTyped(value?: ApiV3OrdersStickersCrossBorderPost200ResponseStickersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file': value['file'],
        'orderId': value['orderId'],
        'parcelId': value['parcelId'],
    };
}

