/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3PassesGet402Response
 */
export interface ApiV3PassesGet402Response {
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof ApiV3PassesGet402Response
     */
    title?: string;
    /**
     * Детали ошибки. Ошибка означает, что на балансе сервиса из [Каталога](https://dev.wildberries.ru/business-solutions) недостаточно средств
     * @type {string}
     * @memberof ApiV3PassesGet402Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the ApiV3PassesGet402Response interface.
 */
export function instanceOfApiV3PassesGet402Response(value: object): value is ApiV3PassesGet402Response {
    return true;
}

export function ApiV3PassesGet402ResponseFromJSON(json: any): ApiV3PassesGet402Response {
    return ApiV3PassesGet402ResponseFromJSONTyped(json, false);
}

export function ApiV3PassesGet402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3PassesGet402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ApiV3PassesGet402ResponseToJSON(json: any): ApiV3PassesGet402Response {
    return ApiV3PassesGet402ResponseToJSONTyped(json, false);
}

export function ApiV3PassesGet402ResponseToJSONTyped(value?: ApiV3PassesGet402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
    };
}

