/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MetaDetailsInner
 */
export interface MetaDetailsInner {
    /**
     * Маркировка
     * @type {string}
     * @memberof MetaDetailsInner
     */
    key?: string;
    /**
     * Значение
     * @type {string}
     * @memberof MetaDetailsInner
     */
    value?: string | null;
    /**
     * Статус:
     * - IMEI
     *   - `filled` — Валидация пройдена
     *   - `deadlineExceeded` — Валидация пройдена
     *   - `optional` — Маркировка не обязательна
     *   - `pending` — Маркировка на проверке
     *   - `required` — Обязательная маркировка не заполнена. Валидация не пройдена
     *   - `imeiInvalidFormat` — Неверный формат маркировки. Валидация не пройдена
     *   - `imeiAlreadySold` — Товар с этим IMEI уже продан. Валидация не пройдена
     * - UIN
     *   - `filled` — Валидация пройдена
     *   - `deadlineExceeded` — Валидация пройдена
     *   - `optional` — Маркировка не обязательна
     *   - `pending` — Маркировка на проверке
     *   - `uinMaySell` — Валидация пройдена
     *   - `required` — Маркировка обязательна, не заполнена. Валидация не пройдена
     *   - `uinInvalidFormat` — Неверный формат маркировки. Валидация не пройдена
     *   - `uinNotFound` — Не найден в ГИС. Валидация не пройдена
     *   - `uinBadStatus` — Некорректный статус партии. Валидация не пройдена
     *   - `uinBadProcess` — Некорректная стадия обработки. Валидация не пройдена
     *   - `uinBadStatusAndBadProcess` — Некорректный статус партии. Некорректная стадия обработки. Валидация не пройдена
     * - SGTIN
     *   - `filled` — Валидация пройдена
     *   - `deadlineExceeded` — Валидация пройдена
     *   - `optional` — Маркировка не обязательна
     *   - `pending` — Маркировка на проверке
     *   - `required` — Маркировка обязательна, не заполнена. Валидация не пройдена
     *   - `sgtinInvalidFormat` — Неверный формат маркировки. Валидация не пройдена
     *   - `sgtinNotFound` — Маркировка не найдена в [Честном Знаке](https://chestnyznak.ru). Валидация не пройдена
     *   - `sgtinEmitted` —  Маркировка эмитирована. Валидация не пройдена
     *   - `sgtinApplied` — Не пройдена процедура Ввод в оборот. Валидация не пройдена
     *   - `sgtinWrittenOff` — Списан. Валидация не пройдена
     *   - `sgtinRetired` — Выбыл. Валидация не пройдена
     *   - `sgtinDisaggregated` — Расформирован. Валидация не пройдена
     *   - `sgtinAppliedNotPaid` — Не оплачен. Валидация не пройдена
     * - GTIN
     *   - `filled` — Валидация пройдена
     *   - `optional` — Маркировка не обязательна
     *   - `required` — Маркировка обязательна, не заполнена. Валидация не пройдена
     * - Expiration
     *   - `filled` — Валидация пройдена
     *   - `optional` — Маркировка не обязательна
     *   - `required` — Маркировка обязательна, не заполнена. Валидация не пройдена
     * - Customs declaration
     *   - `filled` — Валидация пройдена
     *   - `required` — Маркировка обязательна, не заполнена. Валидация не пройдена
     * 
     * @type {string}
     * @memberof MetaDetailsInner
     */
    decision?: string;
}

/**
 * Check if a given object implements the MetaDetailsInner interface.
 */
export function instanceOfMetaDetailsInner(value: object): value is MetaDetailsInner {
    return true;
}

export function MetaDetailsInnerFromJSON(json: any): MetaDetailsInner {
    return MetaDetailsInnerFromJSONTyped(json, false);
}

export function MetaDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'decision': json['decision'] == null ? undefined : json['decision'],
    };
}

export function MetaDetailsInnerToJSON(json: any): MetaDetailsInner {
    return MetaDetailsInnerToJSONTyped(json, false);
}

export function MetaDetailsInnerToJSONTyped(value?: MetaDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'decision': value['decision'],
    };
}

