/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * <div class=\"description_important\"> <b>Методы для работы со сборочными заданиями модели DBW (Доставка курьером WB) теперь на <a href=\"https://dev.wildberries.ru/release-notes?id=312\">отдельном контуре</a>.</b> </div>   В разделе заказов FBS (Fulfillment by Seller) вам доступны методы:   1. Управления [сборочными заданиями](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS): информация о сборочных заданиях, метаданные, стикеры и так далее.   2. Управления [поставками заказов](/openapi/orders-fbs#tag/Postavki-FBS) продавца на склады WB.   3. Заказа [пропусков](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB. <br> <div class=\"description_important\">     Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Номер грузовой таможенной декларации
 * @export
 * @interface MetaCustomsDeclaration
 */
export interface MetaCustomsDeclaration {
    /**
     * 
     * @type {string}
     * @memberof MetaCustomsDeclaration
     */
    value?: string | null;
}

/**
 * Check if a given object implements the MetaCustomsDeclaration interface.
 */
export function instanceOfMetaCustomsDeclaration(value: object): value is MetaCustomsDeclaration {
    return true;
}

export function MetaCustomsDeclarationFromJSON(json: any): MetaCustomsDeclaration {
    return MetaCustomsDeclarationFromJSONTyped(json, false);
}

export function MetaCustomsDeclarationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaCustomsDeclaration {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function MetaCustomsDeclarationToJSON(json: any): MetaCustomsDeclaration {
    return MetaCustomsDeclarationToJSONTyped(json, false);
}

export function MetaCustomsDeclarationToJSONTyped(value?: MetaCustomsDeclaration | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

