/* tslint:disable */
/* eslint-disable */
/**
 * Заказы FBS
 * С помощью методов раздела Заказы FBS (Fulfillment by Seller) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-fbs#tag/Sborochnye-zadaniya-FBS) и их статусах, отменять сборочные задания, получать стикеры   - добавлять, редактировать и удалять [метаданные](/openapi/orders-fbs#tag/Metadannye-FBS) сборочных заданий   - управлять [поставками](/openapi/orders-fbs#tag/Postavki-FBS)   - создавать, редактировать и удалять [пропуска](/openapi/orders-fbs#tag/Propuska-FBS) на склады WB  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/127\">инструкции</a> по работе с <strong>заказами FBS</strong> </div>  <div class=\"description_important\">   Узнать больше о заказах FBS можно в <a href=\"https://seller.wildberries.ru/instructions/ru/ru/category/b3e60238-fd4c-49ce-8668-ff688725a12d\">справочном центре</a> </div> 
 *
 * The version of the OpenAPI document: order
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner
 */
export interface Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    /**
     * Метаданные
     * @type {string}
     * @memberof Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner
     */
    key?: string;
    /**
     * Значение метаданных
     * @type {string}
     * @memberof Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner
     */
    value?: string;
    /**
     * Статус проверки:
     * - IMEI
     *   - `pending` — Маркировка на проверке
     *   - `required` — Обязательная маркировка не заполнена
     *   - `imeiInvalidFormat` — Неверный формат маркировки
     *   - `imeiAlreadySold` — Товар с этим IMEI уже продан
     * - UIN
     *   - `required` — Обязательная маркировка не заполнена
     *   - `pending` — Маркировка на проверке
     *   - `required` — Маркировка обязательна, не заполнена
     *   - `uinInvalidFormat` — Неверный формат маркировки
     *   - `uinNotFound` — Не найден в ГИС
     *   - `uinBadStatus` — Некорректный статус партии
     *   - `uinBadProcess` — Некорректная стадия обработки
     *   - `uinBadStatusAndBadProcess` — Некорректный статус партии. Некорректная стадия обработки
     * - SGTIN
     *   - `required` — Обязательная маркировка не заполнена
     *   - `pending` — Маркировка на проверке
     *   - `sgtinInvalidFormat` — Неверный формат маркировки
     *   - `sgtinNotFound` — Маркировка не найдена в [Честном Знаке](https://chestnyznak.ru)
     *   - `sgtinEmitted` —  Маркировка эмитирована
     *   - `sgtinApplied` — Не пройдена процедура Ввод в оборот
     *   - `sgtinWrittenOff` — Списан
     *   - `sgtinRetired` — Выбыл
     *   - `sgtinWithdrawn` — Выбыл
     *   - `sgtinDisaggregation` — Расформирован
     *   - `sgtinDisaggregated` — Расформирован
     *   - `sgtinAppliedNotPaid` — Не оплачен
     * - GTIN
     *   - `required` — Маркировка обязательна, не заполнена
     * - Expiration
     *   - `required` — Маркировка обязательна, не заполнена
     * - Customs declaration
     *   - `required` — Маркировка обязательна, не заполнена
     * 
     * @type {string}
     * @memberof Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner
     */
    decision?: string;
}

/**
 * Check if a given object implements the Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner interface.
 */
export function instanceOfModel409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner(value: object): value is Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    return true;
}

export function Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerFromJSON(json: any): Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    return Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerFromJSONTyped(json, false);
}

export function Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
        'decision': json['decision'] == null ? undefined : json['decision'],
    };
}

export function Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerToJSON(json: any): Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner {
    return Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerToJSONTyped(json, false);
}

export function Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInnerToJSONTyped(value?: Model409SupplyDeliverErrorDataOrdersInnerMetaDetailsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'key': value['key'],
        'value': value['value'],
        'decision': value['decision'],
    };
}

