/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvV2AutoStatWordsGet200Response {
    /// Исключения (минус-фразы) для товаров из кампании. Можно задать помощью метода [установка/удаление минус-фраз](./ru/openapi/promotion#tag/Parametry-kampanij/paths/~1adv~1v1~1search~1set-phrase/post) или в настройках кампании в личном кабинете
    #[serde(rename = "excluded", skip_serializing_if = "Option::is_none")]
    pub excluded: Option<Vec<String>>,
    /// Кластеры ключевых фраз
    #[serde(rename = "clusters", skip_serializing_if = "Option::is_none")]
    pub clusters: Option<Vec<models::AdvV2AutoStatWordsGet200ResponseClustersInner>>,
}

impl AdvV2AutoStatWordsGet200Response {
    pub fn new() -> AdvV2AutoStatWordsGet200Response {
        AdvV2AutoStatWordsGet200Response {
            excluded: None,
            clusters: None,
        }
    }
}

