/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvV1StatWordsGet200ResponseStatInner {
    /// ID кампании в системе WB
    #[serde(rename = "advertId", skip_serializing_if = "Option::is_none")]
    pub advert_id: Option<i32>,
    /// Ключевая фраза
    #[serde(rename = "keyword", skip_serializing_if = "Option::is_none")]
    pub keyword: Option<String>,
    /// Поле перманентно отключено
    #[serde(rename = "advertName", skip_serializing_if = "Option::is_none")]
    pub advert_name: Option<String>,
    /// Название кампании
    #[serde(rename = "campaignName", skip_serializing_if = "Option::is_none")]
    pub campaign_name: Option<String>,
    /// Дата запуска кампании
    #[serde(rename = "begin", skip_serializing_if = "Option::is_none")]
    pub begin: Option<String>,
    /// Дата завершения кампании
    #[serde(rename = "end", skip_serializing_if = "Option::is_none")]
    pub end: Option<String>,
    /// Количество просмотров
    #[serde(rename = "views", skip_serializing_if = "Option::is_none")]
    pub views: Option<i32>,
    /// Количество кликов
    #[serde(rename = "clicks", skip_serializing_if = "Option::is_none")]
    pub clicks: Option<i32>,
    /// Частота — отношение количества просмотров к количеству уникальных пользователей
    #[serde(rename = "frq", skip_serializing_if = "Option::is_none")]
    pub frq: Option<i32>,
    /// Кликабельность — отношение числа кликов к количеству показов, % 
    #[serde(rename = "ctr", skip_serializing_if = "Option::is_none")]
    pub ctr: Option<f64>,
    /// Стоимость клика, ₽
    #[serde(rename = "cpc", skip_serializing_if = "Option::is_none")]
    pub cpc: Option<f64>,
    /// Длительность кампании, в секундах
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<i32>,
    /// Затраты, ₽
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<f64>,
}

impl AdvV1StatWordsGet200ResponseStatInner {
    pub fn new() -> AdvV1StatWordsGet200ResponseStatInner {
        AdvV1StatWordsGet200ResponseStatInner {
            advert_id: None,
            keyword: None,
            advert_name: None,
            campaign_name: None,
            begin: None,
            end: None,
            views: None,
            clicks: None,
            frq: None,
            ctr: None,
            cpc: None,
            duration: None,
            sum: None,
        }
    }
}

