/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AdvV1StatWordsGet200ResponseWords : Блок информации по ключевым фразам
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdvV1StatWordsGet200ResponseWords {
    /// Фразовое соответствие (минус фразы)
    #[serde(rename = "phrase", skip_serializing_if = "Option::is_none")]
    pub phrase: Option<Vec<String>>,
    /// Точное соответствие (минус фразы)
    #[serde(rename = "strong", skip_serializing_if = "Option::is_none")]
    pub strong: Option<Vec<String>>,
    /// Минус фразы из поиска
    #[serde(rename = "excluded", skip_serializing_if = "Option::is_none")]
    pub excluded: Option<Vec<String>>,
    /// Фиксированные фразы
    #[serde(rename = "pluse", skip_serializing_if = "Option::is_none")]
    pub pluse: Option<Vec<String>>,
    /// Блок со статистикой по ключевым фразам
    #[serde(rename = "keywords", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Vec<models::AdvV1StatWordsGet200ResponseWordsKeywordsInner>>,
    /// Фиксированные ключевые фразы (`true` — включены, `false` — выключены) 
    #[serde(rename = "fixed", skip_serializing_if = "Option::is_none")]
    pub fixed: Option<bool>,
}

impl AdvV1StatWordsGet200ResponseWords {
    /// Блок информации по ключевым фразам
    pub fn new() -> AdvV1StatWordsGet200ResponseWords {
        AdvV1StatWordsGet200ResponseWords {
            phrase: None,
            strong: None,
            excluded: None,
            pluse: None,
            keywords: None,
            fixed: None,
        }
    }
}

