/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DaysV3InnerAppsInner {
    /// Тип платформы:   - `1` — сайт   - `32` — Android   - `64` — IOS 
    #[serde(rename = "appType")]
    pub app_type: AppType,
    /// Количество добавлений товаров в корзину
    #[serde(rename = "atbs")]
    pub atbs: i32,
    /// Отмены, шт.
    #[serde(rename = "canceled")]
    pub canceled: i32,
    /// Количество кликов
    #[serde(rename = "clicks")]
    pub clicks: i32,
    /// Средняя стоимость клика, ₽
    #[serde(rename = "cpc")]
    pub cpc: f64,
    /// CR (conversion rate) — отношение количества заказов к общему количеству кликов
    #[serde(rename = "cr")]
    pub cr: f64,
    /// CTR (click-through rate) — отношение числа кликов к количеству показов в процентах
    #[serde(rename = "ctr")]
    pub ctr: f64,
    /// Блок статистики по артикулам WB
    #[serde(rename = "nms")]
    pub nms: Vec<models::DaysV3InnerAppsInnerNmsInner>,
    /// Количество заказов
    #[serde(rename = "orders")]
    pub orders: i32,
    /// Количество заказанных товаров, шт.
    #[serde(rename = "shks")]
    pub shks: i32,
    /// Затраты, ₽
    #[serde(rename = "sum")]
    pub sum: f64,
    /// Заказов на сумму, ₽
    #[serde(rename = "sum_price")]
    pub sum_price: f64,
    /// Количество просмотров
    #[serde(rename = "views")]
    pub views: i32,
}

impl DaysV3InnerAppsInner {
    pub fn new(app_type: AppType, atbs: i32, canceled: i32, clicks: i32, cpc: f64, cr: f64, ctr: f64, nms: Vec<models::DaysV3InnerAppsInnerNmsInner>, orders: i32, shks: i32, sum: f64, sum_price: f64, views: i32) -> DaysV3InnerAppsInner {
        DaysV3InnerAppsInner {
            app_type,
            atbs,
            canceled,
            clicks,
            cpc,
            cr,
            ctr,
            nms,
            orders,
            shks,
            sum,
            sum_price,
            views,
        }
    }
}
/// Тип платформы:   - `1` — сайт   - `32` — Android   - `64` — IOS 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AppType {
    #[serde(rename = "1")]
    Variant1,
    #[serde(rename = "32")]
    Variant32,
    #[serde(rename = "64")]
    Variant64,
}

impl Default for AppType {
    fn default() -> AppType {
        Self::Variant1
    }
}

