/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">   Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  <div class=\"api-block\">  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media)   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями   3. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний   4. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний   5. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij)   6. Устанавливать [рекомендации](/openapi/promotion#tag/recommendations) для товаров  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд.  </div> 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetRecomResDataInner {
    /// Артикул WB
    #[serde(rename = "nmId")]
    pub nm_id: i32,
    /// ID для [объединённых](https://dev.wildberries.ru/knowledge-base/articles/019d49a4-1320-71bb-9dac-8ba07e7177ce/rabota-s-tovarami#obuedinenie-i-razuedinenie-kartochek-tovarov) карточек товаров
    #[serde(rename = "imtId")]
    pub imt_id: i32,
    /// Артикул продавца
    #[serde(rename = "vendorCode")]
    pub vendor_code: String,
    /// Бренд
    #[serde(rename = "brandName")]
    pub brand_name: String,
    /// Дата и время последнего обновления рекомендаций
    #[serde(rename = "updatedAt", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Количество изображений в карточке товара
    #[serde(rename = "picsCount")]
    pub pics_count: i32,
    /// Название товара
    #[serde(rename = "title")]
    pub title: String,
    /// Предмет
    #[serde(rename = "subjectName")]
    pub subject_name: String,
    /// URL основного изображения в карточке товара
    #[serde(rename = "pic")]
    pub pic: String,
    /// Количество рекомендуемых товаров
    #[serde(rename = "recomCount")]
    pub recom_count: i32,
    /// Список URL основных изображений рекомендуемых товаров
    #[serde(rename = "recomPics")]
    pub recom_pics: Vec<String>,
    /// Список `nmId` рекомендуемых товаров
    #[serde(rename = "recomNms")]
    pub recom_nms: Vec<i32>,
}

impl GetRecomResDataInner {
    pub fn new(nm_id: i32, imt_id: i32, vendor_code: String, brand_name: String, pics_count: i32, title: String, subject_name: String, pic: String, recom_count: i32, recom_pics: Vec<String>, recom_nms: Vec<i32>) -> GetRecomResDataInner {
        GetRecomResDataInner {
            nm_id,
            imt_id,
            vendor_code,
            brand_name,
            updated_at: None,
            pics_count,
            title,
            subject_name,
            pic,
            recom_count,
            recom_pics,
            recom_nms,
        }
    }
}

