/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseInfoAdvertType8AutoParams {
    #[serde(rename = "subject", skip_serializing_if = "Option::is_none")]
    pub subject: Option<Box<models::ResponseInfoAdvertType8AutoParamsSubject>>,
    /// Внутренняя (системная) сущность (пол + предмет)
    #[serde(rename = "sets", skip_serializing_if = "Option::is_none")]
    pub sets: Option<Vec<models::ResponseInfoAdvertType8AutoParamsSetsInner>>,
    #[serde(rename = "menus", skip_serializing_if = "Option::is_none")]
    pub menus: Option<Vec<models::ResponseInfoAdvertType8AutoParamsMenusInner>>,
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<Box<models::ResponseInfoAdvertType8AutoParamsActive>>,
    /// Ставки карточек товаров 
    #[serde(rename = "nmCPM", skip_serializing_if = "Option::is_none")]
    pub nm_cpm: Option<Vec<models::ResponseInfoAdvertType8AutoParamsNmCpmInner>>,
    /// Артикулы WB
    #[serde(rename = "nms", skip_serializing_if = "Option::is_none")]
    pub nms: Option<Vec<i32>>,
    /// Ставка, указанная при создании кампании.<br> Поле актуально только для кампаний, созданных через API. 
    #[serde(rename = "cpm", skip_serializing_if = "Option::is_none")]
    pub cpm: Option<i32>,
}

impl ResponseInfoAdvertType8AutoParams {
    pub fn new() -> ResponseInfoAdvertType8AutoParams {
        ResponseInfoAdvertType8AutoParams {
            subject: None,
            sets: None,
            menus: None,
            active: None,
            nm_cpm: None,
            nms: None,
            cpm: None,
        }
    }
}

