/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseInfoAdvertType8 {
    /// Дата завершения кампании
    #[serde(rename = "endTime", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    /// Дата создания кампании
    #[serde(rename = "createTime", skip_serializing_if = "Option::is_none")]
    pub create_time: Option<String>,
    /// Дата последнего изменения кампании
    #[serde(rename = "changeTime", skip_serializing_if = "Option::is_none")]
    pub change_time: Option<String>,
    /// Дата последнего запуска кампании
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(rename = "autoParams", skip_serializing_if = "Option::is_none")]
    pub auto_params: Option<Box<models::ResponseInfoAdvertType8AutoParams>>,
    /// Название кампании
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Не используется
    #[serde(rename = "dailyBudget", skip_serializing_if = "Option::is_none")]
    pub daily_budget: Option<i32>,
    /// ID кампании
    #[serde(rename = "advertId", skip_serializing_if = "Option::is_none")]
    pub advert_id: Option<i32>,
    /// Статус кампании: - `-1` — удалена, процесс удаления будет завершён в течение 10 минут - `4` — готова к запуску - `7` — завершена - `8` — отменена - `9` — активна - `11` — на паузе 
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<i32>,
    /// Тип кампании:   - `8` — единая ставка 
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<i32>,
    /// Модель оплаты: - `cpm` — за показы 
    #[serde(rename = "paymentType", skip_serializing_if = "Option::is_none")]
    pub payment_type: Option<String>,
}

impl ResponseInfoAdvertType8 {
    pub fn new() -> ResponseInfoAdvertType8 {
        ResponseInfoAdvertType8 {
            end_time: None,
            create_time: None,
            change_time: None,
            start_time: None,
            auto_params: None,
            name: None,
            daily_budget: None,
            advert_id: None,
            status: None,
            r#type: None,
            payment_type: None,
        }
    }
}

