/*
 * Маркетинг и продвижение
 *
 * <div class=\"description_important\">     Узнать больше о маркетинге и продвижении можно в <a href=\"https://seller.wildberries.ru/instructions/category/59d92bd3-6ea0-40f2-b762-ca8835d7d42e?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e\">справочном центре</a> </div>  Методы маркетинга и продвижения позволяют:   1. Получать информацию о кампаниях [продвижения](/openapi/promotion#tag/Kampanii) и [медиакампаниях](/openapi/promotion#tag/Media).   2. [Создавать](/openapi/promotion#tag/Sozdanie-kampanij) и [управлять](/openapi/promotion#tag/Upravlenie-kampaniyami) кампаниями.   3. Настраивать [параметры](/openapi/promotion#tag/Parametry-kampanij) кампаний — кластеры фраз, продвигаемые товары и так далее.   4. Управлять [финансами](/openapi/promotion#tag/Finansy) кампаний.   5. Выгружать [статистику](/openapi/promotion#tag/Statistika) кампаний продвижения и медиакампаний.   6. Работать с [календарём акций](/openapi/promotion#tag/Kalendar-akcij).  Данные синхронизируются с базой раз в 3 минуты. Статусы кампаний меняются раз в минуту. Ставки кампаний меняются раз в 30 секунд. 
 *
 * The version of the OpenAPI document: promotion
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ResponseWithDateInner {
    /// Даты, за которые нужно получить информацию
    #[serde(rename = "dates", skip_serializing_if = "Option::is_none")]
    pub dates: Option<Vec<String>>,
    /// Количество просмотров. <br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "views", skip_serializing_if = "Option::is_none")]
    pub views: Option<i32>,
    /// Количество кликов.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "clicks", skip_serializing_if = "Option::is_none")]
    pub clicks: Option<i32>,
    /// Показатель кликабельности.<br> Отношение числа кликов к количеству показов. Выражается в процентах<br> За все дни, по всем артикулам WB и платформам<br> 
    #[serde(rename = "ctr", skip_serializing_if = "Option::is_none")]
    pub ctr: Option<f64>,
    /// Средняя стоимость клика, ₽.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "cpc", skip_serializing_if = "Option::is_none")]
    pub cpc: Option<f64>,
    /// Затраты, ₽.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "sum", skip_serializing_if = "Option::is_none")]
    pub sum: Option<f64>,
    /// Количество добавлений товаров в корзину.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "atbs", skip_serializing_if = "Option::is_none")]
    pub atbs: Option<i32>,
    /// Количество заказов.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "orders", skip_serializing_if = "Option::is_none")]
    pub orders: Option<i32>,
    /// CR(conversion rate) — это отношение количества заказов к общему количеству посещений кампании.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "cr", skip_serializing_if = "Option::is_none")]
    pub cr: Option<f64>,
    /// Количество заказанных товаров, шт.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "shks", skip_serializing_if = "Option::is_none")]
    pub shks: Option<i32>,
    /// Заказов на сумму, ₽.<br> За все дни, по всем артикулам WB и платформам 
    #[serde(rename = "sum_price", skip_serializing_if = "Option::is_none")]
    pub sum_price: Option<f64>,
    /// Статистка по дням
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<Vec<models::DaysInner>>,
    /// Статистика по средней позиции товара на страницах поисковой выдачи и каталога (для кампаний с единой ставкой)
    #[serde(rename = "boosterStats", skip_serializing_if = "Option::is_none")]
    pub booster_stats: Option<Vec<models::BoosterStatsInner>>,
    /// ID кампании
    #[serde(rename = "advertId", skip_serializing_if = "Option::is_none")]
    pub advert_id: Option<i32>,
}

impl ResponseWithDateInner {
    pub fn new() -> ResponseWithDateInner {
        ResponseWithDateInner {
            dates: None,
            views: None,
            clicks: None,
            ctr: None,
            cpc: None,
            sum: None,
            atbs: None,
            orders: None,
            cr: None,
            shks: None,
            sum_price: None,
            days: None,
            booster_stats: None,
            advert_id: None,
        }
    }
}

