/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiBaseMetaGtin : GTIN
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBaseMetaGtin {
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
}

impl ApiBaseMetaGtin {
    /// GTIN
    pub fn new() -> ApiBaseMetaGtin {
        ApiBaseMetaGtin {
            value: None,
        }
    }
}

