/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOrdersMetaResponse {
    /// Метаданные сборочных заданий
    #[serde(rename = "meta")]
    pub meta: Vec<models::ApiOrderMetaV2>,
}

impl ApiOrdersMetaResponse {
    pub fn new(meta: Vec<models::ApiOrderMetaV2>) -> ApiOrdersMetaResponse {
        ApiOrdersMetaResponse {
            meta,
        }
    }
}

