/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiImei {
    /// ID сборочного задания
    #[serde(rename = "orderId")]
    pub order_id: i32,
    /// IMEI
    #[serde(rename = "imei")]
    pub imei: String,
}

impl ApiImei {
    pub fn new(order_id: i32, imei: String) -> ApiImei {
        ApiImei {
            order_id,
            imei,
        }
    }
}

