/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBaseMeta {
    #[serde(rename = "gtin", skip_serializing_if = "Option::is_none")]
    pub gtin: Option<Box<models::ApiBaseMetaGtin>>,
    #[serde(rename = "imei", skip_serializing_if = "Option::is_none")]
    pub imei: Option<Box<models::ApiBaseMetaImei>>,
    #[serde(rename = "sgtin", skip_serializing_if = "Option::is_none")]
    pub sgtin: Option<Box<models::ApiBaseMetaSgtin>>,
    #[serde(rename = "uin", skip_serializing_if = "Option::is_none")]
    pub uin: Option<Box<models::ApiBaseMetaUin>>,
}

impl ApiBaseMeta {
    pub fn new() -> ApiBaseMeta {
        ApiBaseMeta {
            gtin: None,
            imei: None,
            sgtin: None,
            uin: None,
        }
    }
}

