/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiBatchErrorResponse {
    /// Код ошибки
    #[serde(rename = "code")]
    pub code: i32,
    /// - `NotFound` — сборочное задание не найдено - `StatusMismatch` — операция невозможна для этого статуса сборочного задания 
    #[serde(rename = "detail")]
    pub detail: String,
}

impl ApiBatchErrorResponse {
    pub fn new(code: i32, detail: String) -> ApiBatchErrorResponse {
        ApiBatchErrorResponse {
            code,
            detail,
        }
    }
}

