/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiUinRequest {
    /// УИН
    #[serde(rename = "uin", skip_serializing_if = "Option::is_none")]
    pub uin: Option<String>,
}

impl ApiUinRequest {
    pub fn new() -> ApiUinRequest {
        ApiUinRequest {
            uin: None,
        }
    }
}

