/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiMetaSetResponses {
    /// Уникальный ID запроса
    #[serde(rename = "requestId", deserialize_with = "Option::deserialize")]
    pub request_id: Option<serde_json::Value>,
    #[serde(rename = "results")]
    pub results: Vec<models::ApiMetaSetResponse>,
}

impl ApiMetaSetResponses {
    pub fn new(request_id: Option<serde_json::Value>, results: Vec<models::ApiMetaSetResponse>) -> ApiMetaSetResponses {
        ApiMetaSetResponses {
            request_id,
            results,
        }
    }
}

