/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiCheckedIdentity {
    /// Принадлежит ли заказ покупателю:   - `true` — принадлежит   - `false` — значение не применяется. Если заказ не принадлежит покупателю, вы получите ответ со статус-кодом `409` 
    #[serde(rename = "ok", skip_serializing_if = "Option::is_none")]
    pub ok: Option<bool>,
}

impl ApiCheckedIdentity {
    pub fn new() -> ApiCheckedIdentity {
        ApiCheckedIdentity {
            ok: None,
        }
    }
}

