/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOrdersImeiSetRequest {
    #[serde(rename = "orders")]
    pub orders: Vec<models::ApiImei>,
}

impl ApiOrdersImeiSetRequest {
    pub fn new(orders: Vec<models::ApiImei>) -> ApiOrdersImeiSetRequest {
        ApiOrdersImeiSetRequest {
            orders,
        }
    }
}

