/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiSgtinsRequest {
    /// Массив кодов маркировки. Допускается от 16 до 135 символов для кода одной маркировки
    #[serde(rename = "sgtins", skip_serializing_if = "Option::is_none")]
    pub sgtins: Option<Vec<String>>,
}

impl ApiSgtinsRequest {
    pub fn new() -> ApiSgtinsRequest {
        ApiSgtinsRequest {
            sgtins: None,
        }
    }
}

