/*
 * Заказы Самовывоз
 *
 * Управление [сборочными заданиями](/openapi/in-store-pickup#tag/Sborochnye-zadaniya-Samovyvoz) и [метаданными](/openapi/in-store-pickup#tag/Metadannye-Samovyvoz) заказов модели Самовывоз. 
 *
 * The version of the OpenAPI document: instorepickup
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiOrderStatus {
    /// ID сборочного задания
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Статус сборочного задания, установленный продавцом
    #[serde(rename = "supplierStatus", skip_serializing_if = "Option::is_none")]
    pub supplier_status: Option<String>,
    /// Статус сборочного задания в системе WB
    #[serde(rename = "wbStatus", skip_serializing_if = "Option::is_none")]
    pub wb_status: Option<String>,
}

impl ApiOrderStatus {
    pub fn new() -> ApiOrderStatus {
        ApiOrderStatus {
            id: None,
            supplier_status: None,
            wb_status: None,
        }
    }
}

