/* tslint:disable */
/* eslint-disable */
/**
 * Заказы DBW
 * С помощью методов Заказы DBW (Доставка курьером WB) вы можете:   - получать информацию о [сборочных заданиях](/openapi/orders-dbw#tag/Sborochnye-zadaniya-DBW), управлять статусами и отменять сборочные задания   - получать, добавлять, редактировать и удалять [метаданные](/openapi/orders-dbw#tag/Metadannye-DBW) сборочных заданий  <div class=\"description_ref\">   Узнать, как использовать методы в бизнес-кейсах, можно в <a href=\"https://dev.wildberries.ru/news/241\">инструкции</a> по работе с <strong>заказами DBW</strong> </div> 
 *
 * The version of the OpenAPI document: ordersdbw
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiV3DbwOrdersNewGet402Response
 */
export interface ApiV3DbwOrdersNewGet402Response {
    /**
     * Заголовок ошибки
     * @type {string}
     * @memberof ApiV3DbwOrdersNewGet402Response
     */
    title?: string;
    /**
     * Детали ошибки. Ошибка означает, что на балансе сервиса из [Каталога](https://dev.wildberries.ru/business-solutions) недостаточно средств
     * @type {string}
     * @memberof ApiV3DbwOrdersNewGet402Response
     */
    detail?: string;
}

/**
 * Check if a given object implements the ApiV3DbwOrdersNewGet402Response interface.
 */
export function instanceOfApiV3DbwOrdersNewGet402Response(value: object): value is ApiV3DbwOrdersNewGet402Response {
    return true;
}

export function ApiV3DbwOrdersNewGet402ResponseFromJSON(json: any): ApiV3DbwOrdersNewGet402Response {
    return ApiV3DbwOrdersNewGet402ResponseFromJSONTyped(json, false);
}

export function ApiV3DbwOrdersNewGet402ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV3DbwOrdersNewGet402Response {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'detail': json['detail'] == null ? undefined : json['detail'],
    };
}

export function ApiV3DbwOrdersNewGet402ResponseToJSON(json: any): ApiV3DbwOrdersNewGet402Response {
    return ApiV3DbwOrdersNewGet402ResponseToJSONTyped(json, false);
}

export function ApiV3DbwOrdersNewGet402ResponseToJSONTyped(value?: ApiV3DbwOrdersNewGet402Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'detail': value['detail'],
    };
}

